[type.svg]
extend-glob = ["*.svg"]
check-file = false

[type.png]
extend-glob = ["*.png"]
check-file = false

[default.extend-words]
"Parms" = "Parms"
"PARMS" = "PARMS"

[default.extend-identifiers]
"Parms" = "Parms"
"PARMS" = "PARMS"

[default.extend-words]
# Allow "Encrypter" as it is a valid function name in Go's crypto/cipher package.
Encrypter = "Encrypter"