//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: sut.proto

package proto

import (
	common_definitions "github.com/openconfig/attestz/proto/common_definitions"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AttestDeviceRequest contains connection parameters, target hardware
// specifications, and cryptographic parameters required to execute the Attestz
// remote attestation workflow against a DUT.
type AttestDeviceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target IP address or resolvable hostname (FQDN) of the Device Under
	// Test (DUT).
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Target port for the gNSI/Attestz service running on the DUT.
	// Defaults to "9339" (gNSI port) if unspecified.
	Port string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	// The control card roles to attest on the DUT (e.g., [ACTIVE, STANDBY]).
	// The types of control cards supported (e.g., ACTIVE, STANDBY, CHASSIS)
	// depend on the DUT.
	//   - ACTIVE: Primary supervisor or single control processor.
	//   - STANDBY: Backup supervisor in dual-supervisor modular chassis.
	//   - CHASSIS: Physical chassis enclosure module (proxied via the ACTIVE
	//     card).
	ControlCardRoles []common_definitions.ControlCardRole `protobuf:"varint,3,rep,packed,name=control_card_roles,json=controlCardRoles,proto3,enum=openconfig.attestz.ControlCardRole" json:"control_card_roles,omitempty"`
	// Cryptographically secure random challenge nonce generated by the verifier
	// (Controller) to ensure quote freshness and prevent replay attacks during
	// PCR quoting.
	Nonce []byte `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Hash algorithm of the TPM 2.0 PCR bank to quote (e.g.,
	// TPM_2_0_HASH_ALGO_SHA384).
	HashAlgo      common_definitions.Tpm20HashAlgo `protobuf:"varint,5,opt,name=hash_algo,json=hashAlgo,proto3,enum=openconfig.attestz.Tpm20HashAlgo" json:"hash_algo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestDeviceRequest) Reset() {
	*x = AttestDeviceRequest{}
	mi := &file_sut_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestDeviceRequest) ProtoMessage() {}

func (x *AttestDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sut_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestDeviceRequest.ProtoReflect.Descriptor instead.
func (*AttestDeviceRequest) Descriptor() ([]byte, []int) {
	return file_sut_proto_rawDescGZIP(), []int{0}
}

func (x *AttestDeviceRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AttestDeviceRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *AttestDeviceRequest) GetControlCardRoles() []common_definitions.ControlCardRole {
	if x != nil {
		return x.ControlCardRoles
	}
	return nil
}

func (x *AttestDeviceRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *AttestDeviceRequest) GetHashAlgo() common_definitions.Tpm20HashAlgo {
	if x != nil {
		return x.HashAlgo
	}
	return common_definitions.Tpm20HashAlgo(0)
}

// AttestDeviceResponse reports the outcome of the Attestz attestation workflow.
type AttestDeviceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Information and attestation status for each control card attempted.
	CardResults   []*ControlCardAttestationResult `protobuf:"bytes,1,rep,name=card_results,json=cardResults,proto3" json:"card_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestDeviceResponse) Reset() {
	*x = AttestDeviceResponse{}
	mi := &file_sut_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestDeviceResponse) ProtoMessage() {}

func (x *AttestDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sut_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestDeviceResponse.ProtoReflect.Descriptor instead.
func (*AttestDeviceResponse) Descriptor() ([]byte, []int) {
	return file_sut_proto_rawDescGZIP(), []int{1}
}

func (x *AttestDeviceResponse) GetCardResults() []*ControlCardAttestationResult {
	if x != nil {
		return x.CardResults
	}
	return nil
}

// ControlCardAttestationResult carries the outcome and artifacts for a single
// card.
type ControlCardAttestationResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The control card role that was attested (ACTIVE, STANDBY, or CHASSIS).
	ControlCardRole common_definitions.ControlCardRole `protobuf:"varint,1,opt,name=control_card_role,json=controlCardRole,proto3,enum=openconfig.attestz.ControlCardRole" json:"control_card_role,omitempty"`
	// The status of this specific card:
	//   - OK (0): Card was successfully attested (oIAK cert verified, PCR quote
	//     signature verified, and PCR values matched expected digests).
	//   - FAILED_PRECONDITION: Attestation verification failed on evidence
	//     presented by the DUT (e.g., invalid oIAK cert, quote signature
	//     verification failed, nonce mismatch, or PCR value mismatch).
	//   - UNAVAILABLE: DUT communication or Attest RPC failed for this card.
	Status        *status.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlCardAttestationResult) Reset() {
	*x = ControlCardAttestationResult{}
	mi := &file_sut_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlCardAttestationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCardAttestationResult) ProtoMessage() {}

func (x *ControlCardAttestationResult) ProtoReflect() protoreflect.Message {
	mi := &file_sut_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCardAttestationResult.ProtoReflect.Descriptor instead.
func (*ControlCardAttestationResult) Descriptor() ([]byte, []int) {
	return file_sut_proto_rawDescGZIP(), []int{2}
}

func (x *ControlCardAttestationResult) GetControlCardRole() common_definitions.ControlCardRole {
	if x != nil {
		return x.ControlCardRole
	}
	return common_definitions.ControlCardRole(0)
}

func (x *ControlCardAttestationResult) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_sut_proto protoreflect.FileDescriptor

const file_sut_proto_rawDesc = "" +
	"\n" +
	"\tsut.proto\x12\x1fopenconfig.attestz.test.attestz\x1a<github.com/openconfig/attestz/proto/common_definitions.proto\x1a\x17google/rpc/status.proto\"\xe6\x01\n" +
	"\x13AttestDeviceRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\tR\x04port\x12Q\n" +
	"\x12control_card_roles\x18\x03 \x03(\x0e2#.openconfig.attestz.ControlCardRoleR\x10controlCardRoles\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\x12>\n" +
	"\thash_algo\x18\x05 \x01(\x0e2!.openconfig.attestz.Tpm20HashAlgoR\bhashAlgo\"x\n" +
	"\x14AttestDeviceResponse\x12`\n" +
	"\fcard_results\x18\x01 \x03(\v2=.openconfig.attestz.test.attestz.ControlCardAttestationResultR\vcardResults\"\x9b\x01\n" +
	"\x1cControlCardAttestationResult\x12O\n" +
	"\x11control_card_role\x18\x01 \x01(\x0e2#.openconfig.attestz.ControlCardRoleR\x0fcontrolCardRole\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.google.rpc.StatusR\x06status2\x89\x01\n" +
	"\n" +
	"Controller\x12{\n" +
	"\fAttestDevice\x124.openconfig.attestz.test.attestz.AttestDeviceRequest\x1a5.openconfig.attestz.test.attestz.AttestDeviceResponseB2Z0github.com/openconfig/attestz/test/attestz/protob\x06proto3"

var (
	file_sut_proto_rawDescOnce sync.Once
	file_sut_proto_rawDescData []byte
)

func file_sut_proto_rawDescGZIP() []byte {
	file_sut_proto_rawDescOnce.Do(func() {
		file_sut_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sut_proto_rawDesc), len(file_sut_proto_rawDesc)))
	})
	return file_sut_proto_rawDescData
}

var file_sut_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sut_proto_goTypes = []any{
	(*AttestDeviceRequest)(nil),             // 0: openconfig.attestz.test.attestz.AttestDeviceRequest
	(*AttestDeviceResponse)(nil),            // 1: openconfig.attestz.test.attestz.AttestDeviceResponse
	(*ControlCardAttestationResult)(nil),    // 2: openconfig.attestz.test.attestz.ControlCardAttestationResult
	(common_definitions.ControlCardRole)(0), // 3: openconfig.attestz.ControlCardRole
	(common_definitions.Tpm20HashAlgo)(0),   // 4: openconfig.attestz.Tpm20HashAlgo
	(*status.Status)(nil),                   // 5: google.rpc.Status
}
var file_sut_proto_depIdxs = []int32{
	3, // 0: openconfig.attestz.test.attestz.AttestDeviceRequest.control_card_roles:type_name -> openconfig.attestz.ControlCardRole
	4, // 1: openconfig.attestz.test.attestz.AttestDeviceRequest.hash_algo:type_name -> openconfig.attestz.Tpm20HashAlgo
	2, // 2: openconfig.attestz.test.attestz.AttestDeviceResponse.card_results:type_name -> openconfig.attestz.test.attestz.ControlCardAttestationResult
	3, // 3: openconfig.attestz.test.attestz.ControlCardAttestationResult.control_card_role:type_name -> openconfig.attestz.ControlCardRole
	5, // 4: openconfig.attestz.test.attestz.ControlCardAttestationResult.status:type_name -> google.rpc.Status
	0, // 5: openconfig.attestz.test.attestz.Controller.AttestDevice:input_type -> openconfig.attestz.test.attestz.AttestDeviceRequest
	1, // 6: openconfig.attestz.test.attestz.Controller.AttestDevice:output_type -> openconfig.attestz.test.attestz.AttestDeviceResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sut_proto_init() }
func file_sut_proto_init() {
	if File_sut_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sut_proto_rawDesc), len(file_sut_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sut_proto_goTypes,
		DependencyIndexes: file_sut_proto_depIdxs,
		MessageInfos:      file_sut_proto_msgTypes,
	}.Build()
	File_sut_proto = out.File
	file_sut_proto_goTypes = nil
	file_sut_proto_depIdxs = nil
}
