//
// Copyright 2023 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" B1IS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: github.com/openconfig/attestz/proto/attestz/tpm_attestz.proto

package attestz

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TpmAttestzService_Attest_FullMethodName = "/openconfig.attestz.TpmAttestzService/Attest"
)

// TpmAttestzServiceClient is the client API for TpmAttestzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service is responsible for TPM attestation workflow on the switch
// owner/administrator side. In this workflow switch owner verifies that the
// device's end-to-end boot state (bootloader, OS, configurations, etc.) matches
// owner's expectations. This approach assumes that expected final PCR values
// were precomputed by the switch owner beforehand and are available during the
// attestation workflow.
// Please consult Readme for more details on the workflow.
type TpmAttestzServiceClient interface {
	// Each control card reports its PCR quotes and oIAK cert, while the switch
	// owner verifies oIAK cert and signature over PCR quotes and matches final
	// PCR values against its expectations.
	Attest(ctx context.Context, in *AttestRequest, opts ...grpc.CallOption) (*AttestResponse, error)
}

type tpmAttestzServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTpmAttestzServiceClient(cc grpc.ClientConnInterface) TpmAttestzServiceClient {
	return &tpmAttestzServiceClient{cc}
}

func (c *tpmAttestzServiceClient) Attest(ctx context.Context, in *AttestRequest, opts ...grpc.CallOption) (*AttestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttestResponse)
	err := c.cc.Invoke(ctx, TpmAttestzService_Attest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TpmAttestzServiceServer is the server API for TpmAttestzService service.
// All implementations must embed UnimplementedTpmAttestzServiceServer
// for forward compatibility.
//
// The service is responsible for TPM attestation workflow on the switch
// owner/administrator side. In this workflow switch owner verifies that the
// device's end-to-end boot state (bootloader, OS, configurations, etc.) matches
// owner's expectations. This approach assumes that expected final PCR values
// were precomputed by the switch owner beforehand and are available during the
// attestation workflow.
// Please consult Readme for more details on the workflow.
type TpmAttestzServiceServer interface {
	// Each control card reports its PCR quotes and oIAK cert, while the switch
	// owner verifies oIAK cert and signature over PCR quotes and matches final
	// PCR values against its expectations.
	Attest(context.Context, *AttestRequest) (*AttestResponse, error)
	mustEmbedUnimplementedTpmAttestzServiceServer()
}

// UnimplementedTpmAttestzServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTpmAttestzServiceServer struct{}

func (UnimplementedTpmAttestzServiceServer) Attest(context.Context, *AttestRequest) (*AttestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Attest not implemented")
}
func (UnimplementedTpmAttestzServiceServer) mustEmbedUnimplementedTpmAttestzServiceServer() {}
func (UnimplementedTpmAttestzServiceServer) testEmbeddedByValue()                           {}

// UnsafeTpmAttestzServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TpmAttestzServiceServer will
// result in compilation errors.
type UnsafeTpmAttestzServiceServer interface {
	mustEmbedUnimplementedTpmAttestzServiceServer()
}

func RegisterTpmAttestzServiceServer(s grpc.ServiceRegistrar, srv TpmAttestzServiceServer) {
	// If the following call panics, it indicates UnimplementedTpmAttestzServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TpmAttestzService_ServiceDesc, srv)
}

func _TpmAttestzService_Attest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmAttestzServiceServer).Attest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TpmAttestzService_Attest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmAttestzServiceServer).Attest(ctx, req.(*AttestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TpmAttestzService_ServiceDesc is the grpc.ServiceDesc for TpmAttestzService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TpmAttestzService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openconfig.attestz.TpmAttestzService",
	HandlerType: (*TpmAttestzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Attest",
			Handler:    _TpmAttestzService_Attest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/openconfig/attestz/proto/attestz/tpm_attestz.proto",
}
