// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: github.com/openconfig/attestz/proto/tpm_attestz.proto

package attestz

import (
	common_definitions "github.com/openconfig/attestz/proto/common_definitions"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttestRequest struct {
	state                protoimpl.MessageState                   `protogen:"open.v1"`
	ControlCardSelection *common_definitions.ControlCardSelection `protobuf:"bytes,1,opt,name=control_card_selection,json=controlCardSelection,proto3" json:"control_card_selection,omitempty"`
	Nonce                []byte                                   `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	HashAlgo             common_definitions.Tpm20HashAlgo         `protobuf:"varint,3,opt,name=hash_algo,json=hashAlgo,proto3,enum=openconfig.attestz.Tpm20HashAlgo" json:"hash_algo,omitempty"`
	PcrIndices           []int32                                  `protobuf:"varint,4,rep,packed,name=pcr_indices,json=pcrIndices,proto3" json:"pcr_indices,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AttestRequest) Reset() {
	*x = AttestRequest{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_attestz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestRequest) ProtoMessage() {}

func (x *AttestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_attestz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestRequest.ProtoReflect.Descriptor instead.
func (*AttestRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_attestz_proto_rawDescGZIP(), []int{0}
}

func (x *AttestRequest) GetControlCardSelection() *common_definitions.ControlCardSelection {
	if x != nil {
		return x.ControlCardSelection
	}
	return nil
}

func (x *AttestRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *AttestRequest) GetHashAlgo() common_definitions.Tpm20HashAlgo {
	if x != nil {
		return x.HashAlgo
	}
	return common_definitions.Tpm20HashAlgo(0)
}

func (x *AttestRequest) GetPcrIndices() []int32 {
	if x != nil {
		return x.PcrIndices
	}
	return nil
}

type AttestResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	ControlCardId *common_definitions.ControlCardVendorId `protobuf:"bytes,1,opt,name=control_card_id,json=controlCardId,proto3" json:"control_card_id,omitempty"`
	// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_attestz.proto.
	OiakCert        string                          `protobuf:"bytes,2,opt,name=oiak_cert,json=oiakCert,proto3" json:"oiak_cert,omitempty"`
	PcrValues       map[int32][]byte                `protobuf:"bytes,3,rep,name=pcr_values,json=pcrValues,proto3" json:"pcr_values,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Quoted          []byte                          `protobuf:"bytes,4,opt,name=quoted,proto3" json:"quoted,omitempty"`
	QuoteSignature  []byte                          `protobuf:"bytes,5,opt,name=quote_signature,json=quoteSignature,proto3" json:"quote_signature,omitempty"`
	OidevidCert     string                          `protobuf:"bytes,6,opt,name=oidevid_cert,json=oidevidCert,proto3" json:"oidevid_cert,omitempty"`
	AttestationCert *AttestResponse_AttestationCert `protobuf:"bytes,7,opt,name=attestation_cert,json=attestationCert,proto3" json:"attestation_cert,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttestResponse) Reset() {
	*x = AttestResponse{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_attestz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestResponse) ProtoMessage() {}

func (x *AttestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_attestz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestResponse.ProtoReflect.Descriptor instead.
func (*AttestResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_attestz_proto_rawDescGZIP(), []int{1}
}

func (x *AttestResponse) GetControlCardId() *common_definitions.ControlCardVendorId {
	if x != nil {
		return x.ControlCardId
	}
	return nil
}

// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_attestz.proto.
func (x *AttestResponse) GetOiakCert() string {
	if x != nil {
		return x.OiakCert
	}
	return ""
}

func (x *AttestResponse) GetPcrValues() map[int32][]byte {
	if x != nil {
		return x.PcrValues
	}
	return nil
}

func (x *AttestResponse) GetQuoted() []byte {
	if x != nil {
		return x.Quoted
	}
	return nil
}

func (x *AttestResponse) GetQuoteSignature() []byte {
	if x != nil {
		return x.QuoteSignature
	}
	return nil
}

func (x *AttestResponse) GetOidevidCert() string {
	if x != nil {
		return x.OidevidCert
	}
	return ""
}

func (x *AttestResponse) GetAttestationCert() *AttestResponse_AttestationCert {
	if x != nil {
		return x.AttestationCert
	}
	return nil
}

type AttestResponse_AttestationCert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*AttestResponse_AttestationCert_AikCert
	//	*AttestResponse_AttestationCert_OiakCert
	Value         isAttestResponse_AttestationCert_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestResponse_AttestationCert) Reset() {
	*x = AttestResponse_AttestationCert{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_attestz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestResponse_AttestationCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestResponse_AttestationCert) ProtoMessage() {}

func (x *AttestResponse_AttestationCert) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_attestz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestResponse_AttestationCert.ProtoReflect.Descriptor instead.
func (*AttestResponse_AttestationCert) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_attestz_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AttestResponse_AttestationCert) GetValue() isAttestResponse_AttestationCert_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AttestResponse_AttestationCert) GetAikCert() string {
	if x != nil {
		if x, ok := x.Value.(*AttestResponse_AttestationCert_AikCert); ok {
			return x.AikCert
		}
	}
	return ""
}

func (x *AttestResponse_AttestationCert) GetOiakCert() string {
	if x != nil {
		if x, ok := x.Value.(*AttestResponse_AttestationCert_OiakCert); ok {
			return x.OiakCert
		}
	}
	return ""
}

type isAttestResponse_AttestationCert_Value interface {
	isAttestResponse_AttestationCert_Value()
}

type AttestResponse_AttestationCert_AikCert struct {
	AikCert string `protobuf:"bytes,1,opt,name=aik_cert,json=aikCert,proto3,oneof"`
}

type AttestResponse_AttestationCert_OiakCert struct {
	OiakCert string `protobuf:"bytes,2,opt,name=oiak_cert,json=oiakCert,proto3,oneof"`
}

func (*AttestResponse_AttestationCert_AikCert) isAttestResponse_AttestationCert_Value() {}

func (*AttestResponse_AttestationCert_OiakCert) isAttestResponse_AttestationCert_Value() {}

var File_github_com_openconfig_attestz_proto_tpm_attestz_proto protoreflect.FileDescriptor

const file_github_com_openconfig_attestz_proto_tpm_attestz_proto_rawDesc = "" +
	"\n" +
	"5github.com/openconfig/attestz/proto/tpm_attestz.proto\x12\x12openconfig.attestz\x1a<github.com/openconfig/attestz/proto/common_definitions.proto\"\xe6\x01\n" +
	"\rAttestRequest\x12^\n" +
	"\x16control_card_selection\x18\x01 \x01(\v2(.openconfig.attestz.ControlCardSelectionR\x14controlCardSelection\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12>\n" +
	"\thash_algo\x18\x03 \x01(\x0e2!.openconfig.attestz.Tpm20HashAlgoR\bhashAlgo\x12\x1f\n" +
	"\vpcr_indices\x18\x04 \x03(\x05R\n" +
	"pcrIndices\"\xad\x04\n" +
	"\x0eAttestResponse\x12O\n" +
	"\x0fcontrol_card_id\x18\x01 \x01(\v2'.openconfig.attestz.ControlCardVendorIdR\rcontrolCardId\x12\x1f\n" +
	"\toiak_cert\x18\x02 \x01(\tB\x02\x18\x01R\boiakCert\x12P\n" +
	"\n" +
	"pcr_values\x18\x03 \x03(\v21.openconfig.attestz.AttestResponse.PcrValuesEntryR\tpcrValues\x12\x16\n" +
	"\x06quoted\x18\x04 \x01(\fR\x06quoted\x12'\n" +
	"\x0fquote_signature\x18\x05 \x01(\fR\x0equoteSignature\x12!\n" +
	"\foidevid_cert\x18\x06 \x01(\tR\voidevidCert\x12]\n" +
	"\x10attestation_cert\x18\a \x01(\v22.openconfig.attestz.AttestResponse.AttestationCertR\x0fattestationCert\x1aV\n" +
	"\x0fAttestationCert\x12\x1b\n" +
	"\baik_cert\x18\x01 \x01(\tH\x00R\aaikCert\x12\x1d\n" +
	"\toiak_cert\x18\x02 \x01(\tH\x00R\boiakCertB\a\n" +
	"\x05value\x1a<\n" +
	"\x0ePcrValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x012d\n" +
	"\x11TpmAttestzService\x12O\n" +
	"\x06Attest\x12!.openconfig.attestz.AttestRequest\x1a\".openconfig.attestz.AttestResponseB\x1fZ\x1dgithub.com/openconfig/attestzb\x06proto3"

var (
	file_github_com_openconfig_attestz_proto_tpm_attestz_proto_rawDescOnce sync.Once
	file_github_com_openconfig_attestz_proto_tpm_attestz_proto_rawDescData []byte
)

func file_github_com_openconfig_attestz_proto_tpm_attestz_proto_rawDescGZIP() []byte {
	file_github_com_openconfig_attestz_proto_tpm_attestz_proto_rawDescOnce.Do(func() {
		file_github_com_openconfig_attestz_proto_tpm_attestz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_openconfig_attestz_proto_tpm_attestz_proto_rawDesc), len(file_github_com_openconfig_attestz_proto_tpm_attestz_proto_rawDesc)))
	})
	return file_github_com_openconfig_attestz_proto_tpm_attestz_proto_rawDescData
}

var file_github_com_openconfig_attestz_proto_tpm_attestz_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_openconfig_attestz_proto_tpm_attestz_proto_goTypes = []any{
	(*AttestRequest)(nil),                  // 0: openconfig.attestz.AttestRequest
	(*AttestResponse)(nil),                 // 1: openconfig.attestz.AttestResponse
	(*AttestResponse_AttestationCert)(nil), // 2: openconfig.attestz.AttestResponse.AttestationCert
	nil,                                    // 3: openconfig.attestz.AttestResponse.PcrValuesEntry
	(*common_definitions.ControlCardSelection)(nil), // 4: openconfig.attestz.ControlCardSelection
	(common_definitions.Tpm20HashAlgo)(0),           // 5: openconfig.attestz.Tpm20HashAlgo
	(*common_definitions.ControlCardVendorId)(nil),  // 6: openconfig.attestz.ControlCardVendorId
}
var file_github_com_openconfig_attestz_proto_tpm_attestz_proto_depIdxs = []int32{
	4, // 0: openconfig.attestz.AttestRequest.control_card_selection:type_name -> openconfig.attestz.ControlCardSelection
	5, // 1: openconfig.attestz.AttestRequest.hash_algo:type_name -> openconfig.attestz.Tpm20HashAlgo
	6, // 2: openconfig.attestz.AttestResponse.control_card_id:type_name -> openconfig.attestz.ControlCardVendorId
	3, // 3: openconfig.attestz.AttestResponse.pcr_values:type_name -> openconfig.attestz.AttestResponse.PcrValuesEntry
	2, // 4: openconfig.attestz.AttestResponse.attestation_cert:type_name -> openconfig.attestz.AttestResponse.AttestationCert
	0, // 5: openconfig.attestz.TpmAttestzService.Attest:input_type -> openconfig.attestz.AttestRequest
	1, // 6: openconfig.attestz.TpmAttestzService.Attest:output_type -> openconfig.attestz.AttestResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_github_com_openconfig_attestz_proto_tpm_attestz_proto_init() }
func file_github_com_openconfig_attestz_proto_tpm_attestz_proto_init() {
	if File_github_com_openconfig_attestz_proto_tpm_attestz_proto != nil {
		return
	}
	file_github_com_openconfig_attestz_proto_tpm_attestz_proto_msgTypes[2].OneofWrappers = []any{
		(*AttestResponse_AttestationCert_AikCert)(nil),
		(*AttestResponse_AttestationCert_OiakCert)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_openconfig_attestz_proto_tpm_attestz_proto_rawDesc), len(file_github_com_openconfig_attestz_proto_tpm_attestz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_openconfig_attestz_proto_tpm_attestz_proto_goTypes,
		DependencyIndexes: file_github_com_openconfig_attestz_proto_tpm_attestz_proto_depIdxs,
		MessageInfos:      file_github_com_openconfig_attestz_proto_tpm_attestz_proto_msgTypes,
	}.Build()
	File_github_com_openconfig_attestz_proto_tpm_attestz_proto = out.File
	file_github_com_openconfig_attestz_proto_tpm_attestz_proto_goTypes = nil
	file_github_com_openconfig_attestz_proto_tpm_attestz_proto_depIdxs = nil
}
