version: "2"
linters:
  enable:
    - goconst
    - gocritic
    - gosec
    - revive
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-blank: true
    gocritic:
      disabled-checks:
        - singleCaseSwitch
        - appendAssign
    revive:
      severity: warning
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  new: true
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - \.pb\.go
