// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: github.com/openconfig/attestz/proto/common_definitions.proto

package attestz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlCardRole int32

const (
	ControlCardRole_CONTROL_CARD_ROLE_UNSPECIFIED ControlCardRole = 0
	ControlCardRole_CONTROL_CARD_ROLE_ACTIVE      ControlCardRole = 1
	ControlCardRole_CONTROL_CARD_ROLE_STANDBY     ControlCardRole = 2
)

// Enum value maps for ControlCardRole.
var (
	ControlCardRole_name = map[int32]string{
		0: "CONTROL_CARD_ROLE_UNSPECIFIED",
		1: "CONTROL_CARD_ROLE_ACTIVE",
		2: "CONTROL_CARD_ROLE_STANDBY",
	}
	ControlCardRole_value = map[string]int32{
		"CONTROL_CARD_ROLE_UNSPECIFIED": 0,
		"CONTROL_CARD_ROLE_ACTIVE":      1,
		"CONTROL_CARD_ROLE_STANDBY":     2,
	}
)

func (x ControlCardRole) Enum() *ControlCardRole {
	p := new(ControlCardRole)
	*p = x
	return p
}

func (x ControlCardRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlCardRole) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_attestz_proto_common_definitions_proto_enumTypes[0].Descriptor()
}

func (ControlCardRole) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_attestz_proto_common_definitions_proto_enumTypes[0]
}

func (x ControlCardRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlCardRole.Descriptor instead.
func (ControlCardRole) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_common_definitions_proto_rawDescGZIP(), []int{0}
}

type Tpm20HashAlgo int32

const (
	Tpm20HashAlgo_TPM_2_0_HASH_ALGO_UNSPECIFIED Tpm20HashAlgo = 0
	Tpm20HashAlgo_TPM_2_0_HASH_ALGO_SHA1        Tpm20HashAlgo = 1
	Tpm20HashAlgo_TPM_2_0_HASH_ALGO_SHA256      Tpm20HashAlgo = 2
	Tpm20HashAlgo_TPM_2_0_HASH_ALGO_SHA384      Tpm20HashAlgo = 3
	Tpm20HashAlgo_TPM_2_0_HASH_ALGO_SHA512      Tpm20HashAlgo = 4
)

// Enum value maps for Tpm20HashAlgo.
var (
	Tpm20HashAlgo_name = map[int32]string{
		0: "TPM_2_0_HASH_ALGO_UNSPECIFIED",
		1: "TPM_2_0_HASH_ALGO_SHA1",
		2: "TPM_2_0_HASH_ALGO_SHA256",
		3: "TPM_2_0_HASH_ALGO_SHA384",
		4: "TPM_2_0_HASH_ALGO_SHA512",
	}
	Tpm20HashAlgo_value = map[string]int32{
		"TPM_2_0_HASH_ALGO_UNSPECIFIED": 0,
		"TPM_2_0_HASH_ALGO_SHA1":        1,
		"TPM_2_0_HASH_ALGO_SHA256":      2,
		"TPM_2_0_HASH_ALGO_SHA384":      3,
		"TPM_2_0_HASH_ALGO_SHA512":      4,
	}
)

func (x Tpm20HashAlgo) Enum() *Tpm20HashAlgo {
	p := new(Tpm20HashAlgo)
	*p = x
	return p
}

func (x Tpm20HashAlgo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tpm20HashAlgo) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_attestz_proto_common_definitions_proto_enumTypes[1].Descriptor()
}

func (Tpm20HashAlgo) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_attestz_proto_common_definitions_proto_enumTypes[1]
}

func (x Tpm20HashAlgo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tpm20HashAlgo.Descriptor instead.
func (Tpm20HashAlgo) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_common_definitions_proto_rawDescGZIP(), []int{1}
}

type ControlCardVendorId struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ControlCardRole     ControlCardRole        `protobuf:"varint,1,opt,name=control_card_role,json=controlCardRole,proto3,enum=openconfig.attestz.ControlCardRole" json:"control_card_role,omitempty"`
	ControlCardSerial   string                 `protobuf:"bytes,2,opt,name=control_card_serial,json=controlCardSerial,proto3" json:"control_card_serial,omitempty"`
	ControlCardSlot     string                 `protobuf:"bytes,3,opt,name=control_card_slot,json=controlCardSlot,proto3" json:"control_card_slot,omitempty"`
	ChassisManufacturer string                 `protobuf:"bytes,4,opt,name=chassis_manufacturer,json=chassisManufacturer,proto3" json:"chassis_manufacturer,omitempty"`
	ChassisPartNumber   string                 `protobuf:"bytes,5,opt,name=chassis_part_number,json=chassisPartNumber,proto3" json:"chassis_part_number,omitempty"`
	ChassisSerialNumber string                 `protobuf:"bytes,6,opt,name=chassis_serial_number,json=chassisSerialNumber,proto3" json:"chassis_serial_number,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ControlCardVendorId) Reset() {
	*x = ControlCardVendorId{}
	mi := &file_github_com_openconfig_attestz_proto_common_definitions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlCardVendorId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCardVendorId) ProtoMessage() {}

func (x *ControlCardVendorId) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_common_definitions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCardVendorId.ProtoReflect.Descriptor instead.
func (*ControlCardVendorId) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_common_definitions_proto_rawDescGZIP(), []int{0}
}

func (x *ControlCardVendorId) GetControlCardRole() ControlCardRole {
	if x != nil {
		return x.ControlCardRole
	}
	return ControlCardRole_CONTROL_CARD_ROLE_UNSPECIFIED
}

func (x *ControlCardVendorId) GetControlCardSerial() string {
	if x != nil {
		return x.ControlCardSerial
	}
	return ""
}

func (x *ControlCardVendorId) GetControlCardSlot() string {
	if x != nil {
		return x.ControlCardSlot
	}
	return ""
}

func (x *ControlCardVendorId) GetChassisManufacturer() string {
	if x != nil {
		return x.ChassisManufacturer
	}
	return ""
}

func (x *ControlCardVendorId) GetChassisPartNumber() string {
	if x != nil {
		return x.ChassisPartNumber
	}
	return ""
}

func (x *ControlCardVendorId) GetChassisSerialNumber() string {
	if x != nil {
		return x.ChassisSerialNumber
	}
	return ""
}

type ControlCardSelection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ControlCardId:
	//
	//	*ControlCardSelection_Role
	//	*ControlCardSelection_Serial
	//	*ControlCardSelection_Slot
	ControlCardId isControlCardSelection_ControlCardId `protobuf_oneof:"control_card_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlCardSelection) Reset() {
	*x = ControlCardSelection{}
	mi := &file_github_com_openconfig_attestz_proto_common_definitions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlCardSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCardSelection) ProtoMessage() {}

func (x *ControlCardSelection) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_common_definitions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCardSelection.ProtoReflect.Descriptor instead.
func (*ControlCardSelection) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_common_definitions_proto_rawDescGZIP(), []int{1}
}

func (x *ControlCardSelection) GetControlCardId() isControlCardSelection_ControlCardId {
	if x != nil {
		return x.ControlCardId
	}
	return nil
}

func (x *ControlCardSelection) GetRole() ControlCardRole {
	if x != nil {
		if x, ok := x.ControlCardId.(*ControlCardSelection_Role); ok {
			return x.Role
		}
	}
	return ControlCardRole_CONTROL_CARD_ROLE_UNSPECIFIED
}

func (x *ControlCardSelection) GetSerial() string {
	if x != nil {
		if x, ok := x.ControlCardId.(*ControlCardSelection_Serial); ok {
			return x.Serial
		}
	}
	return ""
}

func (x *ControlCardSelection) GetSlot() string {
	if x != nil {
		if x, ok := x.ControlCardId.(*ControlCardSelection_Slot); ok {
			return x.Slot
		}
	}
	return ""
}

type isControlCardSelection_ControlCardId interface {
	isControlCardSelection_ControlCardId()
}

type ControlCardSelection_Role struct {
	Role ControlCardRole `protobuf:"varint,1,opt,name=role,proto3,enum=openconfig.attestz.ControlCardRole,oneof"`
}

type ControlCardSelection_Serial struct {
	Serial string `protobuf:"bytes,2,opt,name=serial,proto3,oneof"`
}

type ControlCardSelection_Slot struct {
	Slot string `protobuf:"bytes,3,opt,name=slot,proto3,oneof"`
}

func (*ControlCardSelection_Role) isControlCardSelection_ControlCardId() {}

func (*ControlCardSelection_Serial) isControlCardSelection_ControlCardId() {}

func (*ControlCardSelection_Slot) isControlCardSelection_ControlCardId() {}

var File_github_com_openconfig_attestz_proto_common_definitions_proto protoreflect.FileDescriptor

const file_github_com_openconfig_attestz_proto_common_definitions_proto_rawDesc = "" +
	"\n" +
	"<github.com/openconfig/attestz/proto/common_definitions.proto\x12\x12openconfig.attestz\"\xd9\x02\n" +
	"\x13ControlCardVendorId\x12O\n" +
	"\x11control_card_role\x18\x01 \x01(\x0e2#.openconfig.attestz.ControlCardRoleR\x0fcontrolCardRole\x12.\n" +
	"\x13control_card_serial\x18\x02 \x01(\tR\x11controlCardSerial\x12*\n" +
	"\x11control_card_slot\x18\x03 \x01(\tR\x0fcontrolCardSlot\x121\n" +
	"\x14chassis_manufacturer\x18\x04 \x01(\tR\x13chassisManufacturer\x12.\n" +
	"\x13chassis_part_number\x18\x05 \x01(\tR\x11chassisPartNumber\x122\n" +
	"\x15chassis_serial_number\x18\x06 \x01(\tR\x13chassisSerialNumber\"\x94\x01\n" +
	"\x14ControlCardSelection\x129\n" +
	"\x04role\x18\x01 \x01(\x0e2#.openconfig.attestz.ControlCardRoleH\x00R\x04role\x12\x18\n" +
	"\x06serial\x18\x02 \x01(\tH\x00R\x06serial\x12\x14\n" +
	"\x04slot\x18\x03 \x01(\tH\x00R\x04slotB\x11\n" +
	"\x0fcontrol_card_id*q\n" +
	"\x0fControlCardRole\x12!\n" +
	"\x1dCONTROL_CARD_ROLE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONTROL_CARD_ROLE_ACTIVE\x10\x01\x12\x1d\n" +
	"\x19CONTROL_CARD_ROLE_STANDBY\x10\x02*\xa8\x01\n" +
	"\rTpm20HashAlgo\x12!\n" +
	"\x1dTPM_2_0_HASH_ALGO_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TPM_2_0_HASH_ALGO_SHA1\x10\x01\x12\x1c\n" +
	"\x18TPM_2_0_HASH_ALGO_SHA256\x10\x02\x12\x1c\n" +
	"\x18TPM_2_0_HASH_ALGO_SHA384\x10\x03\x12\x1c\n" +
	"\x18TPM_2_0_HASH_ALGO_SHA512\x10\x04B\x1fZ\x1dgithub.com/openconfig/attestzb\x06proto3"

var (
	file_github_com_openconfig_attestz_proto_common_definitions_proto_rawDescOnce sync.Once
	file_github_com_openconfig_attestz_proto_common_definitions_proto_rawDescData []byte
)

func file_github_com_openconfig_attestz_proto_common_definitions_proto_rawDescGZIP() []byte {
	file_github_com_openconfig_attestz_proto_common_definitions_proto_rawDescOnce.Do(func() {
		file_github_com_openconfig_attestz_proto_common_definitions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_openconfig_attestz_proto_common_definitions_proto_rawDesc), len(file_github_com_openconfig_attestz_proto_common_definitions_proto_rawDesc)))
	})
	return file_github_com_openconfig_attestz_proto_common_definitions_proto_rawDescData
}

var file_github_com_openconfig_attestz_proto_common_definitions_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_github_com_openconfig_attestz_proto_common_definitions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_openconfig_attestz_proto_common_definitions_proto_goTypes = []any{
	(ControlCardRole)(0),         // 0: openconfig.attestz.ControlCardRole
	(Tpm20HashAlgo)(0),           // 1: openconfig.attestz.Tpm20HashAlgo
	(*ControlCardVendorId)(nil),  // 2: openconfig.attestz.ControlCardVendorId
	(*ControlCardSelection)(nil), // 3: openconfig.attestz.ControlCardSelection
}
var file_github_com_openconfig_attestz_proto_common_definitions_proto_depIdxs = []int32{
	0, // 0: openconfig.attestz.ControlCardVendorId.control_card_role:type_name -> openconfig.attestz.ControlCardRole
	0, // 1: openconfig.attestz.ControlCardSelection.role:type_name -> openconfig.attestz.ControlCardRole
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_openconfig_attestz_proto_common_definitions_proto_init() }
func file_github_com_openconfig_attestz_proto_common_definitions_proto_init() {
	if File_github_com_openconfig_attestz_proto_common_definitions_proto != nil {
		return
	}
	file_github_com_openconfig_attestz_proto_common_definitions_proto_msgTypes[1].OneofWrappers = []any{
		(*ControlCardSelection_Role)(nil),
		(*ControlCardSelection_Serial)(nil),
		(*ControlCardSelection_Slot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_openconfig_attestz_proto_common_definitions_proto_rawDesc), len(file_github_com_openconfig_attestz_proto_common_definitions_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_openconfig_attestz_proto_common_definitions_proto_goTypes,
		DependencyIndexes: file_github_com_openconfig_attestz_proto_common_definitions_proto_depIdxs,
		EnumInfos:         file_github_com_openconfig_attestz_proto_common_definitions_proto_enumTypes,
		MessageInfos:      file_github_com_openconfig_attestz_proto_common_definitions_proto_msgTypes,
	}.Build()
	File_github_com_openconfig_attestz_proto_common_definitions_proto = out.File
	file_github_com_openconfig_attestz_proto_common_definitions_proto_goTypes = nil
	file_github_com_openconfig_attestz_proto_common_definitions_proto_depIdxs = nil
}
