//
// Copyright 2026 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" B1IS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: sut.proto

package proto

import (
	common_definitions "github.com/openconfig/attestz/proto/common_definitions"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollDeviceResponse_Status int32

const (
	EnrollDeviceResponse_STATUS_UNSPECIFIED EnrollDeviceResponse_Status = 0
	EnrollDeviceResponse_STATUS_SUCCESS     EnrollDeviceResponse_Status = 1
	EnrollDeviceResponse_STATUS_FAILURE     EnrollDeviceResponse_Status = 2
)

// Enum value maps for EnrollDeviceResponse_Status.
var (
	EnrollDeviceResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SUCCESS",
		2: "STATUS_FAILURE",
	}
	EnrollDeviceResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_SUCCESS":     1,
		"STATUS_FAILURE":     2,
	}
)

func (x EnrollDeviceResponse_Status) Enum() *EnrollDeviceResponse_Status {
	p := new(EnrollDeviceResponse_Status)
	*p = x
	return p
}

func (x EnrollDeviceResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnrollDeviceResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_sut_proto_enumTypes[0].Descriptor()
}

func (EnrollDeviceResponse_Status) Type() protoreflect.EnumType {
	return &file_sut_proto_enumTypes[0]
}

func (x EnrollDeviceResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnrollDeviceResponse_Status.Descriptor instead.
func (EnrollDeviceResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_sut_proto_rawDescGZIP(), []int{1, 0}
}

// EnrollDeviceRequest contains the connection parameters and target hardware
// specifications required to execute the Enrollz workflow against a DUT.
type EnrollDeviceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target IP address of the Device Under Test (DUT).
	IpAddress string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Optional: Resolvable hostname or FQDN of the DUT.
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Target port for the gNSI service running on the DUT.
	// The default value is "9339" (gNSI port).
	Port string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	// The control card role to enroll (e.g., ACTIVE, STANDBY, CHASSIS).
	//   - ACTIVE: Primary supervisor or single control processor.
	//   - STANDBY: Backup supervisor in dual-supervisor modular chassis.
	//   - CHASSIS: Physical chassis enclosure module (proxied via the ACTIVE
	//     card).
	ControlCardRole common_definitions.ControlCardRole `protobuf:"varint,4,opt,name=control_card_role,json=controlCardRole,proto3,enum=openconfig.attestz.ControlCardRole" json:"control_card_role,omitempty"`
	// The SSL profile identifier on the DUT where the re-certified owner IDevID
	// (oIDevID) certificate will be bound for TLS authentication. Required
	// whenever oIDevID is rotated.
	SslProfileId  string `protobuf:"bytes,5,opt,name=ssl_profile_id,json=sslProfileId,proto3" json:"ssl_profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollDeviceRequest) Reset() {
	*x = EnrollDeviceRequest{}
	mi := &file_sut_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollDeviceRequest) ProtoMessage() {}

func (x *EnrollDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sut_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollDeviceRequest.ProtoReflect.Descriptor instead.
func (*EnrollDeviceRequest) Descriptor() ([]byte, []int) {
	return file_sut_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollDeviceRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *EnrollDeviceRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollDeviceRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *EnrollDeviceRequest) GetControlCardRole() common_definitions.ControlCardRole {
	if x != nil {
		return x.ControlCardRole
	}
	return common_definitions.ControlCardRole(0)
}

func (x *EnrollDeviceRequest) GetSslProfileId() string {
	if x != nil {
		return x.SslProfileId
	}
	return ""
}

// EnrollDeviceResponse reports the outcome of the Enrollz enrollment workflow.
type EnrollDeviceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resulting status of the enrollment procedure.
	Status EnrollDeviceResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=openconfig.attestz.test.EnrollDeviceResponse_Status" json:"status,omitempty"`
	// Optional: Detailed diagnostic or error message if status is FAILURE.
	// Explains specific root causes (e.g., connection failure, certificate
	// validation failure, serial mismatch, or gRPC rotation error).
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollDeviceResponse) Reset() {
	*x = EnrollDeviceResponse{}
	mi := &file_sut_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollDeviceResponse) ProtoMessage() {}

func (x *EnrollDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sut_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollDeviceResponse.ProtoReflect.Descriptor instead.
func (*EnrollDeviceResponse) Descriptor() ([]byte, []int) {
	return file_sut_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollDeviceResponse) GetStatus() EnrollDeviceResponse_Status {
	if x != nil {
		return x.Status
	}
	return EnrollDeviceResponse_STATUS_UNSPECIFIED
}

func (x *EnrollDeviceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_sut_proto protoreflect.FileDescriptor

const file_sut_proto_rawDesc = "" +
	"\n" +
	"\tsut.proto\x12\x17openconfig.attestz.test\x1a<github.com/openconfig/attestz/proto/common_definitions.proto\"\xdb\x01\n" +
	"\x13EnrollDeviceRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12O\n" +
	"\x11control_card_role\x18\x04 \x01(\x0e2#.openconfig.attestz.ControlCardRoleR\x0fcontrolCardRole\x12$\n" +
	"\x0essl_profile_id\x18\x05 \x01(\tR\fsslProfileId\"\xd3\x01\n" +
	"\x14EnrollDeviceResponse\x12L\n" +
	"\x06status\x18\x01 \x01(\x0e24.openconfig.attestz.test.EnrollDeviceResponse.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"H\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x01\x12\x12\n" +
	"\x0eSTATUS_FAILURE\x10\x022y\n" +
	"\n" +
	"Controller\x12k\n" +
	"\fEnrollDevice\x12,.openconfig.attestz.test.EnrollDeviceRequest\x1a-.openconfig.attestz.test.EnrollDeviceResponseB2Z0github.com/openconfig/attestz/test/enrollz/protob\x06proto3"

var (
	file_sut_proto_rawDescOnce sync.Once
	file_sut_proto_rawDescData []byte
)

func file_sut_proto_rawDescGZIP() []byte {
	file_sut_proto_rawDescOnce.Do(func() {
		file_sut_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sut_proto_rawDesc), len(file_sut_proto_rawDesc)))
	})
	return file_sut_proto_rawDescData
}

var file_sut_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sut_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sut_proto_goTypes = []any{
	(EnrollDeviceResponse_Status)(0),        // 0: openconfig.attestz.test.EnrollDeviceResponse.Status
	(*EnrollDeviceRequest)(nil),             // 1: openconfig.attestz.test.EnrollDeviceRequest
	(*EnrollDeviceResponse)(nil),            // 2: openconfig.attestz.test.EnrollDeviceResponse
	(common_definitions.ControlCardRole)(0), // 3: openconfig.attestz.ControlCardRole
}
var file_sut_proto_depIdxs = []int32{
	3, // 0: openconfig.attestz.test.EnrollDeviceRequest.control_card_role:type_name -> openconfig.attestz.ControlCardRole
	0, // 1: openconfig.attestz.test.EnrollDeviceResponse.status:type_name -> openconfig.attestz.test.EnrollDeviceResponse.Status
	1, // 2: openconfig.attestz.test.Controller.EnrollDevice:input_type -> openconfig.attestz.test.EnrollDeviceRequest
	2, // 3: openconfig.attestz.test.Controller.EnrollDevice:output_type -> openconfig.attestz.test.EnrollDeviceResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sut_proto_init() }
func file_sut_proto_init() {
	if File_sut_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sut_proto_rawDesc), len(file_sut_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sut_proto_goTypes,
		DependencyIndexes: file_sut_proto_depIdxs,
		EnumInfos:         file_sut_proto_enumTypes,
		MessageInfos:      file_sut_proto_msgTypes,
	}.Build()
	File_sut_proto = out.File
	file_sut_proto_goTypes = nil
	file_sut_proto_depIdxs = nil
}
