//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: sut.proto

package proto

import (
	common_definitions "github.com/openconfig/attestz/proto/common_definitions"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnrollDeviceRequest contains the connection parameters and target hardware
// specifications required to execute the Enrollz workflow against a DUT.
type EnrollDeviceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target IP address of the Device Under Test (DUT).
	IpAddress string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Optional: Resolvable hostname or FQDN of the DUT.
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Target port for the gNSI service running on the DUT.
	// The default value is "9339" (gNSI port).
	Port string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	// The control card roles to enroll (e.g., [ACTIVE, STANDBY]). The types of
	// control cards supported (e.g., ACTIVE, STANDBY, CHASSIS) depend on the DUT.
	//   - ACTIVE: Primary supervisor or single control processor.
	//   - STANDBY: Backup supervisor in dual-supervisor modular chassis.
	//   - CHASSIS: Physical chassis enclosure module (proxied via the ACTIVE
	//     card).
	ControlCardRoles []common_definitions.ControlCardRole `protobuf:"varint,4,rep,packed,name=control_card_roles,json=controlCardRoles,proto3,enum=openconfig.attestz.ControlCardRole" json:"control_card_roles,omitempty"`
	// The SSL profile identifier on the DUT where the re-certified owner IDevID
	// (oIDevID) certificate will be bound for TLS authentication. Required
	// whenever oIDevID is rotated.
	SslProfileId  string `protobuf:"bytes,5,opt,name=ssl_profile_id,json=sslProfileId,proto3" json:"ssl_profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollDeviceRequest) Reset() {
	*x = EnrollDeviceRequest{}
	mi := &file_sut_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollDeviceRequest) ProtoMessage() {}

func (x *EnrollDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sut_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollDeviceRequest.ProtoReflect.Descriptor instead.
func (*EnrollDeviceRequest) Descriptor() ([]byte, []int) {
	return file_sut_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollDeviceRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *EnrollDeviceRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollDeviceRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *EnrollDeviceRequest) GetControlCardRoles() []common_definitions.ControlCardRole {
	if x != nil {
		return x.ControlCardRoles
	}
	return nil
}

func (x *EnrollDeviceRequest) GetSslProfileId() string {
	if x != nil {
		return x.SslProfileId
	}
	return ""
}

// EnrollDeviceResponse reports the outcome of the Enrollz enrollment workflow.
type EnrollDeviceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Information and status for each control card attempted.
	CardResults   []*ControlCardEnrollmentResult `protobuf:"bytes,1,rep,name=card_results,json=cardResults,proto3" json:"card_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollDeviceResponse) Reset() {
	*x = EnrollDeviceResponse{}
	mi := &file_sut_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollDeviceResponse) ProtoMessage() {}

func (x *EnrollDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sut_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollDeviceResponse.ProtoReflect.Descriptor instead.
func (*EnrollDeviceResponse) Descriptor() ([]byte, []int) {
	return file_sut_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollDeviceResponse) GetCardResults() []*ControlCardEnrollmentResult {
	if x != nil {
		return x.CardResults
	}
	return nil
}

// ControlCardEnrollmentResult carries the outcome and artifacts for a single
// card.
type ControlCardEnrollmentResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The control card role that was enrolled (ACTIVE, STANDBY, or CHASSIS).
	ControlCardRole common_definitions.ControlCardRole `protobuf:"varint,1,opt,name=control_card_role,json=controlCardRole,proto3,enum=openconfig.attestz.ControlCardRole" json:"control_card_role,omitempty"`
	// The status of this specific card:
	// - OK (0): Card was successfully enrolled.
	// - FAILED_PRECONDITION: DUT cert verification failed (e.g. serial mismatch,
	// cert verify failed, etc).
	// - UNAVAILABLE: DUT communication or GetIakCert failed for this card.
	Status        *status.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlCardEnrollmentResult) Reset() {
	*x = ControlCardEnrollmentResult{}
	mi := &file_sut_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlCardEnrollmentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCardEnrollmentResult) ProtoMessage() {}

func (x *ControlCardEnrollmentResult) ProtoReflect() protoreflect.Message {
	mi := &file_sut_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCardEnrollmentResult.ProtoReflect.Descriptor instead.
func (*ControlCardEnrollmentResult) Descriptor() ([]byte, []int) {
	return file_sut_proto_rawDescGZIP(), []int{2}
}

func (x *ControlCardEnrollmentResult) GetControlCardRole() common_definitions.ControlCardRole {
	if x != nil {
		return x.ControlCardRole
	}
	return common_definitions.ControlCardRole(0)
}

func (x *ControlCardEnrollmentResult) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_sut_proto protoreflect.FileDescriptor

const file_sut_proto_rawDesc = "" +
	"\n" +
	"\tsut.proto\x12\x17openconfig.attestz.test\x1a\x17google/rpc/status.proto\x1a<github.com/openconfig/attestz/proto/common_definitions.proto\"\xdd\x01\n" +
	"\x13EnrollDeviceRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12Q\n" +
	"\x12control_card_roles\x18\x04 \x03(\x0e2#.openconfig.attestz.ControlCardRoleR\x10controlCardRoles\x12$\n" +
	"\x0essl_profile_id\x18\x05 \x01(\tR\fsslProfileId\"o\n" +
	"\x14EnrollDeviceResponse\x12W\n" +
	"\fcard_results\x18\x01 \x03(\v24.openconfig.attestz.test.ControlCardEnrollmentResultR\vcardResults\"\x9a\x01\n" +
	"\x1bControlCardEnrollmentResult\x12O\n" +
	"\x11control_card_role\x18\x01 \x01(\x0e2#.openconfig.attestz.ControlCardRoleR\x0fcontrolCardRole\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.google.rpc.StatusR\x06status2y\n" +
	"\n" +
	"Controller\x12k\n" +
	"\fEnrollDevice\x12,.openconfig.attestz.test.EnrollDeviceRequest\x1a-.openconfig.attestz.test.EnrollDeviceResponseB2Z0github.com/openconfig/attestz/test/enrollz/protob\x06proto3"

var (
	file_sut_proto_rawDescOnce sync.Once
	file_sut_proto_rawDescData []byte
)

func file_sut_proto_rawDescGZIP() []byte {
	file_sut_proto_rawDescOnce.Do(func() {
		file_sut_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sut_proto_rawDesc), len(file_sut_proto_rawDesc)))
	})
	return file_sut_proto_rawDescData
}

var file_sut_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sut_proto_goTypes = []any{
	(*EnrollDeviceRequest)(nil),             // 0: openconfig.attestz.test.EnrollDeviceRequest
	(*EnrollDeviceResponse)(nil),            // 1: openconfig.attestz.test.EnrollDeviceResponse
	(*ControlCardEnrollmentResult)(nil),     // 2: openconfig.attestz.test.ControlCardEnrollmentResult
	(common_definitions.ControlCardRole)(0), // 3: openconfig.attestz.ControlCardRole
	(*status.Status)(nil),                   // 4: google.rpc.Status
}
var file_sut_proto_depIdxs = []int32{
	3, // 0: openconfig.attestz.test.EnrollDeviceRequest.control_card_roles:type_name -> openconfig.attestz.ControlCardRole
	2, // 1: openconfig.attestz.test.EnrollDeviceResponse.card_results:type_name -> openconfig.attestz.test.ControlCardEnrollmentResult
	3, // 2: openconfig.attestz.test.ControlCardEnrollmentResult.control_card_role:type_name -> openconfig.attestz.ControlCardRole
	4, // 3: openconfig.attestz.test.ControlCardEnrollmentResult.status:type_name -> google.rpc.Status
	0, // 4: openconfig.attestz.test.Controller.EnrollDevice:input_type -> openconfig.attestz.test.EnrollDeviceRequest
	1, // 5: openconfig.attestz.test.Controller.EnrollDevice:output_type -> openconfig.attestz.test.EnrollDeviceResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sut_proto_init() }
func file_sut_proto_init() {
	if File_sut_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sut_proto_rawDesc), len(file_sut_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sut_proto_goTypes,
		DependencyIndexes: file_sut_proto_depIdxs,
		MessageInfos:      file_sut_proto_msgTypes,
	}.Build()
	File_sut_proto = out.File
	file_sut_proto_goTypes = nil
	file_sut_proto_depIdxs = nil
}
