// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: github.com/openconfig/attestz/proto/tpm_enrollz.proto

package attestz

import (
	common_definitions "github.com/openconfig/attestz/proto/common_definitions"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Key int32

const (
	Key_KEY_UNSPECIFIED Key = 0
	Key_KEY_EK          Key = 1
	Key_KEY_PPK         Key = 2
)

// Enum value maps for Key.
var (
	Key_name = map[int32]string{
		0: "KEY_UNSPECIFIED",
		1: "KEY_EK",
		2: "KEY_PPK",
	}
	Key_value = map[string]int32{
		"KEY_UNSPECIFIED": 0,
		"KEY_EK":          1,
		"KEY_PPK":         2,
	}
)

func (x Key) Enum() *Key {
	p := new(Key)
	*p = x
	return p
}

func (x Key) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Key) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_enumTypes[0].Descriptor()
}

func (Key) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_enumTypes[0]
}

func (x Key) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Key.Descriptor instead.
func (Key) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{0}
}

type KeyTemplate int32

const (
	KeyTemplate_KEY_TEMPLATE_UNSPECIFIED   KeyTemplate = 0
	KeyTemplate_KEY_TEMPLATE_ECC_NIST_P384 KeyTemplate = 1
)

// Enum value maps for KeyTemplate.
var (
	KeyTemplate_name = map[int32]string{
		0: "KEY_TEMPLATE_UNSPECIFIED",
		1: "KEY_TEMPLATE_ECC_NIST_P384",
	}
	KeyTemplate_value = map[string]int32{
		"KEY_TEMPLATE_UNSPECIFIED":   0,
		"KEY_TEMPLATE_ECC_NIST_P384": 1,
	}
)

func (x KeyTemplate) Enum() *KeyTemplate {
	p := new(KeyTemplate)
	*p = x
	return p
}

func (x KeyTemplate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyTemplate) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_enumTypes[1].Descriptor()
}

func (KeyTemplate) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_enumTypes[1]
}

func (x KeyTemplate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyTemplate.Descriptor instead.
func (KeyTemplate) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{1}
}

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_SUCCESS     Status = 1
	Status_STATUS_FAILURE     Status = 2
	Status_STATUS_UNSUPPORTED Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SUCCESS",
		2: "STATUS_FAILURE",
		3: "STATUS_UNSUPPORTED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_SUCCESS":     1,
		"STATUS_FAILURE":     2,
		"STATUS_UNSUPPORTED": 3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_enumTypes[2].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_enumTypes[2]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{2}
}

type GetIakCertRequest struct {
	state                protoimpl.MessageState                   `protogen:"open.v1"`
	ControlCardSelection *common_definitions.ControlCardSelection `protobuf:"bytes,1,opt,name=control_card_selection,json=controlCardSelection,proto3" json:"control_card_selection,omitempty"`
	Nonce                []byte                                   `protobuf:"bytes,2,opt,name=nonce,proto3,oneof" json:"nonce,omitempty"`
	HashAlgo             *common_definitions.Tpm20HashAlgo        `protobuf:"varint,3,opt,name=hash_algo,json=hashAlgo,proto3,enum=openconfig.attestz.Tpm20HashAlgo,oneof" json:"hash_algo,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetIakCertRequest) Reset() {
	*x = GetIakCertRequest{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIakCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIakCertRequest) ProtoMessage() {}

func (x *GetIakCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIakCertRequest.ProtoReflect.Descriptor instead.
func (*GetIakCertRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{0}
}

func (x *GetIakCertRequest) GetControlCardSelection() *common_definitions.ControlCardSelection {
	if x != nil {
		return x.ControlCardSelection
	}
	return nil
}

func (x *GetIakCertRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *GetIakCertRequest) GetHashAlgo() common_definitions.Tpm20HashAlgo {
	if x != nil && x.HashAlgo != nil {
		return *x.HashAlgo
	}
	return common_definitions.Tpm20HashAlgo(0)
}

type GetIakCertResponse struct {
	state                       protoimpl.MessageState                  `protogen:"open.v1"`
	ControlCardId               *common_definitions.ControlCardVendorId `protobuf:"bytes,1,opt,name=control_card_id,json=controlCardId,proto3" json:"control_card_id,omitempty"`
	IakCert                     string                                  `protobuf:"bytes,2,opt,name=iak_cert,json=iakCert,proto3" json:"iak_cert,omitempty"`
	IdevidCert                  string                                  `protobuf:"bytes,3,opt,name=idevid_cert,json=idevidCert,proto3" json:"idevid_cert,omitempty"`
	NonceSignature              []byte                                  `protobuf:"bytes,4,opt,name=nonce_signature,json=nonceSignature,proto3,oneof" json:"nonce_signature,omitempty"`
	AtomicCertRotationSupported bool                                    `protobuf:"varint,5,opt,name=atomic_cert_rotation_supported,json=atomicCertRotationSupported,proto3" json:"atomic_cert_rotation_supported,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *GetIakCertResponse) Reset() {
	*x = GetIakCertResponse{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIakCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIakCertResponse) ProtoMessage() {}

func (x *GetIakCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIakCertResponse.ProtoReflect.Descriptor instead.
func (*GetIakCertResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{1}
}

func (x *GetIakCertResponse) GetControlCardId() *common_definitions.ControlCardVendorId {
	if x != nil {
		return x.ControlCardId
	}
	return nil
}

func (x *GetIakCertResponse) GetIakCert() string {
	if x != nil {
		return x.IakCert
	}
	return ""
}

func (x *GetIakCertResponse) GetIdevidCert() string {
	if x != nil {
		return x.IdevidCert
	}
	return ""
}

func (x *GetIakCertResponse) GetNonceSignature() []byte {
	if x != nil {
		return x.NonceSignature
	}
	return nil
}

func (x *GetIakCertResponse) GetAtomicCertRotationSupported() bool {
	if x != nil {
		return x.AtomicCertRotationSupported
	}
	return false
}

type RotateOIakCertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_enrollz.proto.
	ControlCardSelection *common_definitions.ControlCardSelection `protobuf:"bytes,1,opt,name=control_card_selection,json=controlCardSelection,proto3" json:"control_card_selection,omitempty"`
	// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_enrollz.proto.
	OiakCert string `protobuf:"bytes,2,opt,name=oiak_cert,json=oiakCert,proto3" json:"oiak_cert,omitempty"`
	// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_enrollz.proto.
	OidevidCert   string                   `protobuf:"bytes,3,opt,name=oidevid_cert,json=oidevidCert,proto3" json:"oidevid_cert,omitempty"`
	SslProfileId  string                   `protobuf:"bytes,4,opt,name=ssl_profile_id,json=sslProfileId,proto3" json:"ssl_profile_id,omitempty"`
	Updates       []*ControlCardCertUpdate `protobuf:"bytes,5,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateOIakCertRequest) Reset() {
	*x = RotateOIakCertRequest{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateOIakCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateOIakCertRequest) ProtoMessage() {}

func (x *RotateOIakCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateOIakCertRequest.ProtoReflect.Descriptor instead.
func (*RotateOIakCertRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{2}
}

// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_enrollz.proto.
func (x *RotateOIakCertRequest) GetControlCardSelection() *common_definitions.ControlCardSelection {
	if x != nil {
		return x.ControlCardSelection
	}
	return nil
}

// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_enrollz.proto.
func (x *RotateOIakCertRequest) GetOiakCert() string {
	if x != nil {
		return x.OiakCert
	}
	return ""
}

// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_enrollz.proto.
func (x *RotateOIakCertRequest) GetOidevidCert() string {
	if x != nil {
		return x.OidevidCert
	}
	return ""
}

func (x *RotateOIakCertRequest) GetSslProfileId() string {
	if x != nil {
		return x.SslProfileId
	}
	return ""
}

func (x *RotateOIakCertRequest) GetUpdates() []*ControlCardCertUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type ControlCardCertUpdate struct {
	state                protoimpl.MessageState                   `protogen:"open.v1"`
	ControlCardSelection *common_definitions.ControlCardSelection `protobuf:"bytes,1,opt,name=control_card_selection,json=controlCardSelection,proto3" json:"control_card_selection,omitempty"`
	OiakCert             string                                   `protobuf:"bytes,2,opt,name=oiak_cert,json=oiakCert,proto3" json:"oiak_cert,omitempty"`
	OidevidCert          string                                   `protobuf:"bytes,3,opt,name=oidevid_cert,json=oidevidCert,proto3" json:"oidevid_cert,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ControlCardCertUpdate) Reset() {
	*x = ControlCardCertUpdate{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlCardCertUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCardCertUpdate) ProtoMessage() {}

func (x *ControlCardCertUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCardCertUpdate.ProtoReflect.Descriptor instead.
func (*ControlCardCertUpdate) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{3}
}

func (x *ControlCardCertUpdate) GetControlCardSelection() *common_definitions.ControlCardSelection {
	if x != nil {
		return x.ControlCardSelection
	}
	return nil
}

func (x *ControlCardCertUpdate) GetOiakCert() string {
	if x != nil {
		return x.OiakCert
	}
	return ""
}

func (x *ControlCardCertUpdate) GetOidevidCert() string {
	if x != nil {
		return x.OidevidCert
	}
	return ""
}

type RotateOIakCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateOIakCertResponse) Reset() {
	*x = RotateOIakCertResponse{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateOIakCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateOIakCertResponse) ProtoMessage() {}

func (x *RotateOIakCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateOIakCertResponse.ProtoReflect.Descriptor instead.
func (*RotateOIakCertResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{4}
}

type RotateAIKCertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*RotateAIKCertRequest_IssuerPublicKey
	//	*RotateAIKCertRequest_IssuerCertPayload_
	//	*RotateAIKCertRequest_Finalize
	Value                isRotateAIKCertRequest_Value             `protobuf_oneof:"value"`
	ControlCardSelection *common_definitions.ControlCardSelection `protobuf:"bytes,4,opt,name=control_card_selection,json=controlCardSelection,proto3" json:"control_card_selection,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RotateAIKCertRequest) Reset() {
	*x = RotateAIKCertRequest{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateAIKCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateAIKCertRequest) ProtoMessage() {}

func (x *RotateAIKCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateAIKCertRequest.ProtoReflect.Descriptor instead.
func (*RotateAIKCertRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{5}
}

func (x *RotateAIKCertRequest) GetValue() isRotateAIKCertRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RotateAIKCertRequest) GetIssuerPublicKey() []byte {
	if x != nil {
		if x, ok := x.Value.(*RotateAIKCertRequest_IssuerPublicKey); ok {
			return x.IssuerPublicKey
		}
	}
	return nil
}

func (x *RotateAIKCertRequest) GetIssuerCertPayload() *RotateAIKCertRequest_IssuerCertPayload {
	if x != nil {
		if x, ok := x.Value.(*RotateAIKCertRequest_IssuerCertPayload_); ok {
			return x.IssuerCertPayload
		}
	}
	return nil
}

func (x *RotateAIKCertRequest) GetFinalize() bool {
	if x != nil {
		if x, ok := x.Value.(*RotateAIKCertRequest_Finalize); ok {
			return x.Finalize
		}
	}
	return false
}

func (x *RotateAIKCertRequest) GetControlCardSelection() *common_definitions.ControlCardSelection {
	if x != nil {
		return x.ControlCardSelection
	}
	return nil
}

type isRotateAIKCertRequest_Value interface {
	isRotateAIKCertRequest_Value()
}

type RotateAIKCertRequest_IssuerPublicKey struct {
	IssuerPublicKey []byte `protobuf:"bytes,1,opt,name=issuer_public_key,json=issuerPublicKey,proto3,oneof"`
}

type RotateAIKCertRequest_IssuerCertPayload_ struct {
	IssuerCertPayload *RotateAIKCertRequest_IssuerCertPayload `protobuf:"bytes,2,opt,name=issuer_cert_payload,json=issuerCertPayload,proto3,oneof"`
}

type RotateAIKCertRequest_Finalize struct {
	Finalize bool `protobuf:"varint,3,opt,name=finalize,proto3,oneof"`
}

func (*RotateAIKCertRequest_IssuerPublicKey) isRotateAIKCertRequest_Value() {}

func (*RotateAIKCertRequest_IssuerCertPayload_) isRotateAIKCertRequest_Value() {}

func (*RotateAIKCertRequest_Finalize) isRotateAIKCertRequest_Value() {}

type RotateAIKCertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*RotateAIKCertResponse_ApplicationIdentityRequest
	//	*RotateAIKCertResponse_AikCert
	Value         isRotateAIKCertResponse_Value           `protobuf_oneof:"value"`
	ControlCardId *common_definitions.ControlCardVendorId `protobuf:"bytes,3,opt,name=control_card_id,json=controlCardId,proto3" json:"control_card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateAIKCertResponse) Reset() {
	*x = RotateAIKCertResponse{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateAIKCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateAIKCertResponse) ProtoMessage() {}

func (x *RotateAIKCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateAIKCertResponse.ProtoReflect.Descriptor instead.
func (*RotateAIKCertResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{6}
}

func (x *RotateAIKCertResponse) GetValue() isRotateAIKCertResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RotateAIKCertResponse) GetApplicationIdentityRequest() []byte {
	if x != nil {
		if x, ok := x.Value.(*RotateAIKCertResponse_ApplicationIdentityRequest); ok {
			return x.ApplicationIdentityRequest
		}
	}
	return nil
}

func (x *RotateAIKCertResponse) GetAikCert() string {
	if x != nil {
		if x, ok := x.Value.(*RotateAIKCertResponse_AikCert); ok {
			return x.AikCert
		}
	}
	return ""
}

func (x *RotateAIKCertResponse) GetControlCardId() *common_definitions.ControlCardVendorId {
	if x != nil {
		return x.ControlCardId
	}
	return nil
}

type isRotateAIKCertResponse_Value interface {
	isRotateAIKCertResponse_Value()
}

type RotateAIKCertResponse_ApplicationIdentityRequest struct {
	ApplicationIdentityRequest []byte `protobuf:"bytes,1,opt,name=application_identity_request,json=applicationIdentityRequest,proto3,oneof"`
}

type RotateAIKCertResponse_AikCert struct {
	AikCert string `protobuf:"bytes,2,opt,name=aik_cert,json=aikCert,proto3,oneof"`
}

func (*RotateAIKCertResponse_ApplicationIdentityRequest) isRotateAIKCertResponse_Value() {}

func (*RotateAIKCertResponse_AikCert) isRotateAIKCertResponse_Value() {}

type GetControlCardVendorIDRequest struct {
	state                protoimpl.MessageState                   `protogen:"open.v1"`
	ControlCardSelection *common_definitions.ControlCardSelection `protobuf:"bytes,1,opt,name=control_card_selection,json=controlCardSelection,proto3" json:"control_card_selection,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetControlCardVendorIDRequest) Reset() {
	*x = GetControlCardVendorIDRequest{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetControlCardVendorIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetControlCardVendorIDRequest) ProtoMessage() {}

func (x *GetControlCardVendorIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetControlCardVendorIDRequest.ProtoReflect.Descriptor instead.
func (*GetControlCardVendorIDRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{7}
}

func (x *GetControlCardVendorIDRequest) GetControlCardSelection() *common_definitions.ControlCardSelection {
	if x != nil {
		return x.ControlCardSelection
	}
	return nil
}

type GetControlCardVendorIDResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	ControlCardId *common_definitions.ControlCardVendorId `protobuf:"bytes,1,opt,name=control_card_id,json=controlCardId,proto3" json:"control_card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetControlCardVendorIDResponse) Reset() {
	*x = GetControlCardVendorIDResponse{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetControlCardVendorIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetControlCardVendorIDResponse) ProtoMessage() {}

func (x *GetControlCardVendorIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetControlCardVendorIDResponse.ProtoReflect.Descriptor instead.
func (*GetControlCardVendorIDResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{8}
}

func (x *GetControlCardVendorIDResponse) GetControlCardId() *common_definitions.ControlCardVendorId {
	if x != nil {
		return x.ControlCardId
	}
	return nil
}

type GetIdevidCsrRequest struct {
	state                protoimpl.MessageState                   `protogen:"open.v1"`
	ControlCardSelection *common_definitions.ControlCardSelection `protobuf:"bytes,1,opt,name=control_card_selection,json=controlCardSelection,proto3" json:"control_card_selection,omitempty"`
	Key                  Key                                      `protobuf:"varint,2,opt,name=key,proto3,enum=openconfig.attestz.Key" json:"key,omitempty"`
	KeyTemplate          KeyTemplate                              `protobuf:"varint,3,opt,name=key_template,json=keyTemplate,proto3,enum=openconfig.attestz.KeyTemplate" json:"key_template,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetIdevidCsrRequest) Reset() {
	*x = GetIdevidCsrRequest{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdevidCsrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdevidCsrRequest) ProtoMessage() {}

func (x *GetIdevidCsrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdevidCsrRequest.ProtoReflect.Descriptor instead.
func (*GetIdevidCsrRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{9}
}

func (x *GetIdevidCsrRequest) GetControlCardSelection() *common_definitions.ControlCardSelection {
	if x != nil {
		return x.ControlCardSelection
	}
	return nil
}

func (x *GetIdevidCsrRequest) GetKey() Key {
	if x != nil {
		return x.Key
	}
	return Key_KEY_UNSPECIFIED
}

func (x *GetIdevidCsrRequest) GetKeyTemplate() KeyTemplate {
	if x != nil {
		return x.KeyTemplate
	}
	return KeyTemplate_KEY_TEMPLATE_UNSPECIFIED
}

type CsrResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CsrContents        []byte                 `protobuf:"bytes,1,opt,name=csr_contents,json=csrContents,proto3" json:"csr_contents,omitempty"`
	IdevidSignatureCsr []byte                 `protobuf:"bytes,2,opt,name=idevid_signature_csr,json=idevidSignatureCsr,proto3" json:"idevid_signature_csr,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CsrResponse) Reset() {
	*x = CsrResponse{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsrResponse) ProtoMessage() {}

func (x *CsrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsrResponse.ProtoReflect.Descriptor instead.
func (*CsrResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{10}
}

func (x *CsrResponse) GetCsrContents() []byte {
	if x != nil {
		return x.CsrContents
	}
	return nil
}

func (x *CsrResponse) GetIdevidSignatureCsr() []byte {
	if x != nil {
		return x.IdevidSignatureCsr
	}
	return nil
}

type GetIdevidCsrResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	ControlCardId *common_definitions.ControlCardVendorId `protobuf:"bytes,1,opt,name=control_card_id,json=controlCardId,proto3" json:"control_card_id,omitempty"`
	// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_enrollz.proto.
	CsrContents []byte `protobuf:"bytes,2,opt,name=csr_contents,json=csrContents,proto3" json:"csr_contents,omitempty"`
	// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_enrollz.proto.
	IdevidSignatureCsr []byte       `protobuf:"bytes,3,opt,name=idevid_signature_csr,json=idevidSignatureCsr,proto3" json:"idevid_signature_csr,omitempty"`
	CsrResponse        *CsrResponse `protobuf:"bytes,4,opt,name=csr_response,json=csrResponse,proto3" json:"csr_response,omitempty"`
	Status             Status       `protobuf:"varint,5,opt,name=status,proto3,enum=openconfig.attestz.Status" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetIdevidCsrResponse) Reset() {
	*x = GetIdevidCsrResponse{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdevidCsrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdevidCsrResponse) ProtoMessage() {}

func (x *GetIdevidCsrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdevidCsrResponse.ProtoReflect.Descriptor instead.
func (*GetIdevidCsrResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{11}
}

func (x *GetIdevidCsrResponse) GetControlCardId() *common_definitions.ControlCardVendorId {
	if x != nil {
		return x.ControlCardId
	}
	return nil
}

// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_enrollz.proto.
func (x *GetIdevidCsrResponse) GetCsrContents() []byte {
	if x != nil {
		return x.CsrContents
	}
	return nil
}

// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_enrollz.proto.
func (x *GetIdevidCsrResponse) GetIdevidSignatureCsr() []byte {
	if x != nil {
		return x.IdevidSignatureCsr
	}
	return nil
}

func (x *GetIdevidCsrResponse) GetCsrResponse() *CsrResponse {
	if x != nil {
		return x.CsrResponse
	}
	return nil
}

func (x *GetIdevidCsrResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type HMACChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HmacPubKey    []byte                 `protobuf:"bytes,1,opt,name=hmac_pub_key,json=hmacPubKey,proto3" json:"hmac_pub_key,omitempty"`
	Duplicate     []byte                 `protobuf:"bytes,2,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	InSymSeed     []byte                 `protobuf:"bytes,3,opt,name=in_sym_seed,json=inSymSeed,proto3" json:"in_sym_seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HMACChallenge) Reset() {
	*x = HMACChallenge{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HMACChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HMACChallenge) ProtoMessage() {}

func (x *HMACChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HMACChallenge.ProtoReflect.Descriptor instead.
func (*HMACChallenge) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{12}
}

func (x *HMACChallenge) GetHmacPubKey() []byte {
	if x != nil {
		return x.HmacPubKey
	}
	return nil
}

func (x *HMACChallenge) GetDuplicate() []byte {
	if x != nil {
		return x.Duplicate
	}
	return nil
}

func (x *HMACChallenge) GetInSymSeed() []byte {
	if x != nil {
		return x.InSymSeed
	}
	return nil
}

type ChallengeRequest struct {
	state                protoimpl.MessageState                   `protogen:"open.v1"`
	ControlCardSelection *common_definitions.ControlCardSelection `protobuf:"bytes,1,opt,name=control_card_selection,json=controlCardSelection,proto3" json:"control_card_selection,omitempty"`
	// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_enrollz.proto.
	EncryptedNonce []byte         `protobuf:"bytes,2,opt,name=encrypted_nonce,json=encryptedNonce,proto3" json:"encrypted_nonce,omitempty"`
	Key            Key            `protobuf:"varint,3,opt,name=key,proto3,enum=openconfig.attestz.Key" json:"key,omitempty"`
	Challenge      *HMACChallenge `protobuf:"bytes,4,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChallengeRequest) Reset() {
	*x = ChallengeRequest{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeRequest) ProtoMessage() {}

func (x *ChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeRequest.ProtoReflect.Descriptor instead.
func (*ChallengeRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{13}
}

func (x *ChallengeRequest) GetControlCardSelection() *common_definitions.ControlCardSelection {
	if x != nil {
		return x.ControlCardSelection
	}
	return nil
}

// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_enrollz.proto.
func (x *ChallengeRequest) GetEncryptedNonce() []byte {
	if x != nil {
		return x.EncryptedNonce
	}
	return nil
}

func (x *ChallengeRequest) GetKey() Key {
	if x != nil {
		return x.Key
	}
	return Key_KEY_UNSPECIFIED
}

func (x *ChallengeRequest) GetChallenge() *HMACChallenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type HMACChallengeResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	IakPub                  []byte                 `protobuf:"bytes,1,opt,name=iak_pub,json=iakPub,proto3" json:"iak_pub,omitempty"`
	IakCertifyInfo          []byte                 `protobuf:"bytes,2,opt,name=iak_certify_info,json=iakCertifyInfo,proto3" json:"iak_certify_info,omitempty"`
	IakCertifyInfoSignature []byte                 `protobuf:"bytes,3,opt,name=iak_certify_info_signature,json=iakCertifyInfoSignature,proto3" json:"iak_certify_info_signature,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *HMACChallengeResponse) Reset() {
	*x = HMACChallengeResponse{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HMACChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HMACChallengeResponse) ProtoMessage() {}

func (x *HMACChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HMACChallengeResponse.ProtoReflect.Descriptor instead.
func (*HMACChallengeResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{14}
}

func (x *HMACChallengeResponse) GetIakPub() []byte {
	if x != nil {
		return x.IakPub
	}
	return nil
}

func (x *HMACChallengeResponse) GetIakCertifyInfo() []byte {
	if x != nil {
		return x.IakCertifyInfo
	}
	return nil
}

func (x *HMACChallengeResponse) GetIakCertifyInfoSignature() []byte {
	if x != nil {
		return x.IakCertifyInfoSignature
	}
	return nil
}

type ChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeResp *HMACChallengeResponse `protobuf:"bytes,1,opt,name=challenge_resp,json=challengeResp,proto3" json:"challenge_resp,omitempty"`
	// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_enrollz.proto.
	Nonce         []byte `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{15}
}

func (x *ChallengeResponse) GetChallengeResp() *HMACChallengeResponse {
	if x != nil {
		return x.ChallengeResp
	}
	return nil
}

// Deprecated: Marked as deprecated in github.com/openconfig/attestz/proto/tpm_enrollz.proto.
func (x *ChallengeResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type RotateAIKCertRequest_IssuerCertPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SymmetricKeyBlob []byte                 `protobuf:"bytes,1,opt,name=symmetric_key_blob,json=symmetricKeyBlob,proto3" json:"symmetric_key_blob,omitempty"`
	AikCertBlob      []byte                 `protobuf:"bytes,2,opt,name=aik_cert_blob,json=aikCertBlob,proto3" json:"aik_cert_blob,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RotateAIKCertRequest_IssuerCertPayload) Reset() {
	*x = RotateAIKCertRequest_IssuerCertPayload{}
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateAIKCertRequest_IssuerCertPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateAIKCertRequest_IssuerCertPayload) ProtoMessage() {}

func (x *RotateAIKCertRequest_IssuerCertPayload) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateAIKCertRequest_IssuerCertPayload.ProtoReflect.Descriptor instead.
func (*RotateAIKCertRequest_IssuerCertPayload) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP(), []int{5, 0}
}

func (x *RotateAIKCertRequest_IssuerCertPayload) GetSymmetricKeyBlob() []byte {
	if x != nil {
		return x.SymmetricKeyBlob
	}
	return nil
}

func (x *RotateAIKCertRequest_IssuerCertPayload) GetAikCertBlob() []byte {
	if x != nil {
		return x.AikCertBlob
	}
	return nil
}

var File_github_com_openconfig_attestz_proto_tpm_enrollz_proto protoreflect.FileDescriptor

const file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDesc = "" +
	"\n" +
	"5github.com/openconfig/attestz/proto/tpm_enrollz.proto\x12\x12openconfig.attestz\x1a<github.com/openconfig/attestz/proto/common_definitions.proto\"\xeb\x01\n" +
	"\x11GetIakCertRequest\x12^\n" +
	"\x16control_card_selection\x18\x01 \x01(\v2(.openconfig.attestz.ControlCardSelectionR\x14controlCardSelection\x12\x19\n" +
	"\x05nonce\x18\x02 \x01(\fH\x00R\x05nonce\x88\x01\x01\x12C\n" +
	"\thash_algo\x18\x03 \x01(\x0e2!.openconfig.attestz.Tpm20HashAlgoH\x01R\bhashAlgo\x88\x01\x01B\b\n" +
	"\x06_nonceB\f\n" +
	"\n" +
	"_hash_algo\"\xa8\x02\n" +
	"\x12GetIakCertResponse\x12O\n" +
	"\x0fcontrol_card_id\x18\x01 \x01(\v2'.openconfig.attestz.ControlCardVendorIdR\rcontrolCardId\x12\x19\n" +
	"\biak_cert\x18\x02 \x01(\tR\aiakCert\x12\x1f\n" +
	"\videvid_cert\x18\x03 \x01(\tR\n" +
	"idevidCert\x12,\n" +
	"\x0fnonce_signature\x18\x04 \x01(\fH\x00R\x0enonceSignature\x88\x01\x01\x12C\n" +
	"\x1eatomic_cert_rotation_supported\x18\x05 \x01(\bR\x1batomicCertRotationSupportedB\x12\n" +
	"\x10_nonce_signature\"\xae\x02\n" +
	"\x15RotateOIakCertRequest\x12b\n" +
	"\x16control_card_selection\x18\x01 \x01(\v2(.openconfig.attestz.ControlCardSelectionB\x02\x18\x01R\x14controlCardSelection\x12\x1f\n" +
	"\toiak_cert\x18\x02 \x01(\tB\x02\x18\x01R\boiakCert\x12%\n" +
	"\foidevid_cert\x18\x03 \x01(\tB\x02\x18\x01R\voidevidCert\x12$\n" +
	"\x0essl_profile_id\x18\x04 \x01(\tR\fsslProfileId\x12C\n" +
	"\aupdates\x18\x05 \x03(\v2).openconfig.attestz.ControlCardCertUpdateR\aupdates\"\xb7\x01\n" +
	"\x15ControlCardCertUpdate\x12^\n" +
	"\x16control_card_selection\x18\x01 \x01(\v2(.openconfig.attestz.ControlCardSelectionR\x14controlCardSelection\x12\x1b\n" +
	"\toiak_cert\x18\x02 \x01(\tR\boiakCert\x12!\n" +
	"\foidevid_cert\x18\x03 \x01(\tR\voidevidCert\"\x18\n" +
	"\x16RotateOIakCertResponse\"\xa0\x03\n" +
	"\x14RotateAIKCertRequest\x12,\n" +
	"\x11issuer_public_key\x18\x01 \x01(\fH\x00R\x0fissuerPublicKey\x12l\n" +
	"\x13issuer_cert_payload\x18\x02 \x01(\v2:.openconfig.attestz.RotateAIKCertRequest.IssuerCertPayloadH\x00R\x11issuerCertPayload\x12\x1c\n" +
	"\bfinalize\x18\x03 \x01(\bH\x00R\bfinalize\x12^\n" +
	"\x16control_card_selection\x18\x04 \x01(\v2(.openconfig.attestz.ControlCardSelectionR\x14controlCardSelection\x1ae\n" +
	"\x11IssuerCertPayload\x12,\n" +
	"\x12symmetric_key_blob\x18\x01 \x01(\fR\x10symmetricKeyBlob\x12\"\n" +
	"\raik_cert_blob\x18\x02 \x01(\fR\vaikCertBlobB\a\n" +
	"\x05value\"\xd2\x01\n" +
	"\x15RotateAIKCertResponse\x12B\n" +
	"\x1capplication_identity_request\x18\x01 \x01(\fH\x00R\x1aapplicationIdentityRequest\x12\x1b\n" +
	"\baik_cert\x18\x02 \x01(\tH\x00R\aaikCert\x12O\n" +
	"\x0fcontrol_card_id\x18\x03 \x01(\v2'.openconfig.attestz.ControlCardVendorIdR\rcontrolCardIdB\a\n" +
	"\x05value\"\x7f\n" +
	"\x1dGetControlCardVendorIDRequest\x12^\n" +
	"\x16control_card_selection\x18\x01 \x01(\v2(.openconfig.attestz.ControlCardSelectionR\x14controlCardSelection\"q\n" +
	"\x1eGetControlCardVendorIDResponse\x12O\n" +
	"\x0fcontrol_card_id\x18\x01 \x01(\v2'.openconfig.attestz.ControlCardVendorIdR\rcontrolCardId\"\xe4\x01\n" +
	"\x13GetIdevidCsrRequest\x12^\n" +
	"\x16control_card_selection\x18\x01 \x01(\v2(.openconfig.attestz.ControlCardSelectionR\x14controlCardSelection\x12)\n" +
	"\x03key\x18\x02 \x01(\x0e2\x17.openconfig.attestz.KeyR\x03key\x12B\n" +
	"\fkey_template\x18\x03 \x01(\x0e2\x1f.openconfig.attestz.KeyTemplateR\vkeyTemplate\"b\n" +
	"\vCsrResponse\x12!\n" +
	"\fcsr_contents\x18\x01 \x01(\fR\vcsrContents\x120\n" +
	"\x14idevid_signature_csr\x18\x02 \x01(\fR\x12idevidSignatureCsr\"\xbc\x02\n" +
	"\x14GetIdevidCsrResponse\x12O\n" +
	"\x0fcontrol_card_id\x18\x01 \x01(\v2'.openconfig.attestz.ControlCardVendorIdR\rcontrolCardId\x12%\n" +
	"\fcsr_contents\x18\x02 \x01(\fB\x02\x18\x01R\vcsrContents\x124\n" +
	"\x14idevid_signature_csr\x18\x03 \x01(\fB\x02\x18\x01R\x12idevidSignatureCsr\x12B\n" +
	"\fcsr_response\x18\x04 \x01(\v2\x1f.openconfig.attestz.CsrResponseR\vcsrResponse\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.openconfig.attestz.StatusR\x06status\"o\n" +
	"\rHMACChallenge\x12 \n" +
	"\fhmac_pub_key\x18\x01 \x01(\fR\n" +
	"hmacPubKey\x12\x1c\n" +
	"\tduplicate\x18\x02 \x01(\fR\tduplicate\x12\x1e\n" +
	"\vin_sym_seed\x18\x03 \x01(\fR\tinSymSeed\"\x8b\x02\n" +
	"\x10ChallengeRequest\x12^\n" +
	"\x16control_card_selection\x18\x01 \x01(\v2(.openconfig.attestz.ControlCardSelectionR\x14controlCardSelection\x12+\n" +
	"\x0fencrypted_nonce\x18\x02 \x01(\fB\x02\x18\x01R\x0eencryptedNonce\x12)\n" +
	"\x03key\x18\x03 \x01(\x0e2\x17.openconfig.attestz.KeyR\x03key\x12?\n" +
	"\tchallenge\x18\x04 \x01(\v2!.openconfig.attestz.HMACChallengeR\tchallenge\"\x97\x01\n" +
	"\x15HMACChallengeResponse\x12\x17\n" +
	"\aiak_pub\x18\x01 \x01(\fR\x06iakPub\x12(\n" +
	"\x10iak_certify_info\x18\x02 \x01(\fR\x0eiakCertifyInfo\x12;\n" +
	"\x1aiak_certify_info_signature\x18\x03 \x01(\fR\x17iakCertifyInfoSignature\"\x7f\n" +
	"\x11ChallengeResponse\x12P\n" +
	"\x0echallenge_resp\x18\x01 \x01(\v2).openconfig.attestz.HMACChallengeResponseR\rchallengeResp\x12\x18\n" +
	"\x05nonce\x18\x02 \x01(\fB\x02\x18\x01R\x05nonce*3\n" +
	"\x03Key\x12\x13\n" +
	"\x0fKEY_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06KEY_EK\x10\x01\x12\v\n" +
	"\aKEY_PPK\x10\x02*K\n" +
	"\vKeyTemplate\x12\x1c\n" +
	"\x18KEY_TEMPLATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aKEY_TEMPLATE_ECC_NIST_P384\x10\x01*`\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x01\x12\x12\n" +
	"\x0eSTATUS_FAILURE\x10\x02\x12\x16\n" +
	"\x12STATUS_UNSUPPORTED\x10\x032\x81\x05\n" +
	"\x11TpmEnrollzService\x12[\n" +
	"\n" +
	"GetIakCert\x12%.openconfig.attestz.GetIakCertRequest\x1a&.openconfig.attestz.GetIakCertResponse\x12g\n" +
	"\x0eRotateOIakCert\x12).openconfig.attestz.RotateOIakCertRequest\x1a*.openconfig.attestz.RotateOIakCertResponse\x12h\n" +
	"\rRotateAIKCert\x12(.openconfig.attestz.RotateAIKCertRequest\x1a).openconfig.attestz.RotateAIKCertResponse(\x010\x01\x12a\n" +
	"\fGetIdevidCsr\x12'.openconfig.attestz.GetIdevidCsrRequest\x1a(.openconfig.attestz.GetIdevidCsrResponse\x12X\n" +
	"\tChallenge\x12$.openconfig.attestz.ChallengeRequest\x1a%.openconfig.attestz.ChallengeResponse\x12\x7f\n" +
	"\x16GetControlCardVendorID\x121.openconfig.attestz.GetControlCardVendorIDRequest\x1a2.openconfig.attestz.GetControlCardVendorIDResponseB\x1fZ\x1dgithub.com/openconfig/attestzb\x06proto3"

var (
	file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescOnce sync.Once
	file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescData []byte
)

func file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescGZIP() []byte {
	file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescOnce.Do(func() {
		file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDesc), len(file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDesc)))
	})
	return file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDescData
}

var file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_goTypes = []any{
	(Key)(0),                                        // 0: openconfig.attestz.Key
	(KeyTemplate)(0),                                // 1: openconfig.attestz.KeyTemplate
	(Status)(0),                                     // 2: openconfig.attestz.Status
	(*GetIakCertRequest)(nil),                       // 3: openconfig.attestz.GetIakCertRequest
	(*GetIakCertResponse)(nil),                      // 4: openconfig.attestz.GetIakCertResponse
	(*RotateOIakCertRequest)(nil),                   // 5: openconfig.attestz.RotateOIakCertRequest
	(*ControlCardCertUpdate)(nil),                   // 6: openconfig.attestz.ControlCardCertUpdate
	(*RotateOIakCertResponse)(nil),                  // 7: openconfig.attestz.RotateOIakCertResponse
	(*RotateAIKCertRequest)(nil),                    // 8: openconfig.attestz.RotateAIKCertRequest
	(*RotateAIKCertResponse)(nil),                   // 9: openconfig.attestz.RotateAIKCertResponse
	(*GetControlCardVendorIDRequest)(nil),           // 10: openconfig.attestz.GetControlCardVendorIDRequest
	(*GetControlCardVendorIDResponse)(nil),          // 11: openconfig.attestz.GetControlCardVendorIDResponse
	(*GetIdevidCsrRequest)(nil),                     // 12: openconfig.attestz.GetIdevidCsrRequest
	(*CsrResponse)(nil),                             // 13: openconfig.attestz.CsrResponse
	(*GetIdevidCsrResponse)(nil),                    // 14: openconfig.attestz.GetIdevidCsrResponse
	(*HMACChallenge)(nil),                           // 15: openconfig.attestz.HMACChallenge
	(*ChallengeRequest)(nil),                        // 16: openconfig.attestz.ChallengeRequest
	(*HMACChallengeResponse)(nil),                   // 17: openconfig.attestz.HMACChallengeResponse
	(*ChallengeResponse)(nil),                       // 18: openconfig.attestz.ChallengeResponse
	(*RotateAIKCertRequest_IssuerCertPayload)(nil),  // 19: openconfig.attestz.RotateAIKCertRequest.IssuerCertPayload
	(*common_definitions.ControlCardSelection)(nil), // 20: openconfig.attestz.ControlCardSelection
	(common_definitions.Tpm20HashAlgo)(0),           // 21: openconfig.attestz.Tpm20HashAlgo
	(*common_definitions.ControlCardVendorId)(nil),  // 22: openconfig.attestz.ControlCardVendorId
}
var file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_depIdxs = []int32{
	20, // 0: openconfig.attestz.GetIakCertRequest.control_card_selection:type_name -> openconfig.attestz.ControlCardSelection
	21, // 1: openconfig.attestz.GetIakCertRequest.hash_algo:type_name -> openconfig.attestz.Tpm20HashAlgo
	22, // 2: openconfig.attestz.GetIakCertResponse.control_card_id:type_name -> openconfig.attestz.ControlCardVendorId
	20, // 3: openconfig.attestz.RotateOIakCertRequest.control_card_selection:type_name -> openconfig.attestz.ControlCardSelection
	6,  // 4: openconfig.attestz.RotateOIakCertRequest.updates:type_name -> openconfig.attestz.ControlCardCertUpdate
	20, // 5: openconfig.attestz.ControlCardCertUpdate.control_card_selection:type_name -> openconfig.attestz.ControlCardSelection
	19, // 6: openconfig.attestz.RotateAIKCertRequest.issuer_cert_payload:type_name -> openconfig.attestz.RotateAIKCertRequest.IssuerCertPayload
	20, // 7: openconfig.attestz.RotateAIKCertRequest.control_card_selection:type_name -> openconfig.attestz.ControlCardSelection
	22, // 8: openconfig.attestz.RotateAIKCertResponse.control_card_id:type_name -> openconfig.attestz.ControlCardVendorId
	20, // 9: openconfig.attestz.GetControlCardVendorIDRequest.control_card_selection:type_name -> openconfig.attestz.ControlCardSelection
	22, // 10: openconfig.attestz.GetControlCardVendorIDResponse.control_card_id:type_name -> openconfig.attestz.ControlCardVendorId
	20, // 11: openconfig.attestz.GetIdevidCsrRequest.control_card_selection:type_name -> openconfig.attestz.ControlCardSelection
	0,  // 12: openconfig.attestz.GetIdevidCsrRequest.key:type_name -> openconfig.attestz.Key
	1,  // 13: openconfig.attestz.GetIdevidCsrRequest.key_template:type_name -> openconfig.attestz.KeyTemplate
	22, // 14: openconfig.attestz.GetIdevidCsrResponse.control_card_id:type_name -> openconfig.attestz.ControlCardVendorId
	13, // 15: openconfig.attestz.GetIdevidCsrResponse.csr_response:type_name -> openconfig.attestz.CsrResponse
	2,  // 16: openconfig.attestz.GetIdevidCsrResponse.status:type_name -> openconfig.attestz.Status
	20, // 17: openconfig.attestz.ChallengeRequest.control_card_selection:type_name -> openconfig.attestz.ControlCardSelection
	0,  // 18: openconfig.attestz.ChallengeRequest.key:type_name -> openconfig.attestz.Key
	15, // 19: openconfig.attestz.ChallengeRequest.challenge:type_name -> openconfig.attestz.HMACChallenge
	17, // 20: openconfig.attestz.ChallengeResponse.challenge_resp:type_name -> openconfig.attestz.HMACChallengeResponse
	3,  // 21: openconfig.attestz.TpmEnrollzService.GetIakCert:input_type -> openconfig.attestz.GetIakCertRequest
	5,  // 22: openconfig.attestz.TpmEnrollzService.RotateOIakCert:input_type -> openconfig.attestz.RotateOIakCertRequest
	8,  // 23: openconfig.attestz.TpmEnrollzService.RotateAIKCert:input_type -> openconfig.attestz.RotateAIKCertRequest
	12, // 24: openconfig.attestz.TpmEnrollzService.GetIdevidCsr:input_type -> openconfig.attestz.GetIdevidCsrRequest
	16, // 25: openconfig.attestz.TpmEnrollzService.Challenge:input_type -> openconfig.attestz.ChallengeRequest
	10, // 26: openconfig.attestz.TpmEnrollzService.GetControlCardVendorID:input_type -> openconfig.attestz.GetControlCardVendorIDRequest
	4,  // 27: openconfig.attestz.TpmEnrollzService.GetIakCert:output_type -> openconfig.attestz.GetIakCertResponse
	7,  // 28: openconfig.attestz.TpmEnrollzService.RotateOIakCert:output_type -> openconfig.attestz.RotateOIakCertResponse
	9,  // 29: openconfig.attestz.TpmEnrollzService.RotateAIKCert:output_type -> openconfig.attestz.RotateAIKCertResponse
	14, // 30: openconfig.attestz.TpmEnrollzService.GetIdevidCsr:output_type -> openconfig.attestz.GetIdevidCsrResponse
	18, // 31: openconfig.attestz.TpmEnrollzService.Challenge:output_type -> openconfig.attestz.ChallengeResponse
	11, // 32: openconfig.attestz.TpmEnrollzService.GetControlCardVendorID:output_type -> openconfig.attestz.GetControlCardVendorIDResponse
	27, // [27:33] is the sub-list for method output_type
	21, // [21:27] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_init() }
func file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_init() {
	if File_github_com_openconfig_attestz_proto_tpm_enrollz_proto != nil {
		return
	}
	file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[0].OneofWrappers = []any{}
	file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[1].OneofWrappers = []any{}
	file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[5].OneofWrappers = []any{
		(*RotateAIKCertRequest_IssuerPublicKey)(nil),
		(*RotateAIKCertRequest_IssuerCertPayload_)(nil),
		(*RotateAIKCertRequest_Finalize)(nil),
	}
	file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes[6].OneofWrappers = []any{
		(*RotateAIKCertResponse_ApplicationIdentityRequest)(nil),
		(*RotateAIKCertResponse_AikCert)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDesc), len(file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_goTypes,
		DependencyIndexes: file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_depIdxs,
		EnumInfos:         file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_enumTypes,
		MessageInfos:      file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_msgTypes,
	}.Build()
	File_github_com_openconfig_attestz_proto_tpm_enrollz_proto = out.File
	file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_goTypes = nil
	file_github_com_openconfig_attestz_proto_tpm_enrollz_proto_depIdxs = nil
}
