// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.10
// source: github.com/openconfig/attestz/proto/tpm_enrollz.proto

package attestz

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TpmEnrollzServiceClient is the client API for TpmEnrollzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TpmEnrollzServiceClient interface {
	GetIakCert(ctx context.Context, in *GetIakCertRequest, opts ...grpc.CallOption) (*GetIakCertResponse, error)
	RotateOIakCert(ctx context.Context, in *RotateOIakCertRequest, opts ...grpc.CallOption) (*RotateOIakCertResponse, error)
	RotateAIKCert(ctx context.Context, opts ...grpc.CallOption) (TpmEnrollzService_RotateAIKCertClient, error)
}

type tpmEnrollzServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTpmEnrollzServiceClient(cc grpc.ClientConnInterface) TpmEnrollzServiceClient {
	return &tpmEnrollzServiceClient{cc}
}

func (c *tpmEnrollzServiceClient) GetIakCert(ctx context.Context, in *GetIakCertRequest, opts ...grpc.CallOption) (*GetIakCertResponse, error) {
	out := new(GetIakCertResponse)
	err := c.cc.Invoke(ctx, "/openconfig.attestz.TpmEnrollzService/GetIakCert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmEnrollzServiceClient) RotateOIakCert(ctx context.Context, in *RotateOIakCertRequest, opts ...grpc.CallOption) (*RotateOIakCertResponse, error) {
	out := new(RotateOIakCertResponse)
	err := c.cc.Invoke(ctx, "/openconfig.attestz.TpmEnrollzService/RotateOIakCert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmEnrollzServiceClient) RotateAIKCert(ctx context.Context, opts ...grpc.CallOption) (TpmEnrollzService_RotateAIKCertClient, error) {
	stream, err := c.cc.NewStream(ctx, &TpmEnrollzService_ServiceDesc.Streams[0], "/openconfig.attestz.TpmEnrollzService/RotateAIKCert", opts...)
	if err != nil {
		return nil, err
	}
	x := &tpmEnrollzServiceRotateAIKCertClient{stream}
	return x, nil
}

type TpmEnrollzService_RotateAIKCertClient interface {
	Send(*RotateAIKCertRequest) error
	Recv() (*RotateAIKCertResponse, error)
	grpc.ClientStream
}

type tpmEnrollzServiceRotateAIKCertClient struct {
	grpc.ClientStream
}

func (x *tpmEnrollzServiceRotateAIKCertClient) Send(m *RotateAIKCertRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tpmEnrollzServiceRotateAIKCertClient) Recv() (*RotateAIKCertResponse, error) {
	m := new(RotateAIKCertResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TpmEnrollzServiceServer is the server API for TpmEnrollzService service.
// All implementations must embed UnimplementedTpmEnrollzServiceServer
// for forward compatibility
type TpmEnrollzServiceServer interface {
	GetIakCert(context.Context, *GetIakCertRequest) (*GetIakCertResponse, error)
	RotateOIakCert(context.Context, *RotateOIakCertRequest) (*RotateOIakCertResponse, error)
	RotateAIKCert(TpmEnrollzService_RotateAIKCertServer) error
	mustEmbedUnimplementedTpmEnrollzServiceServer()
}

// UnimplementedTpmEnrollzServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTpmEnrollzServiceServer struct {
}

func (UnimplementedTpmEnrollzServiceServer) GetIakCert(context.Context, *GetIakCertRequest) (*GetIakCertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIakCert not implemented")
}
func (UnimplementedTpmEnrollzServiceServer) RotateOIakCert(context.Context, *RotateOIakCertRequest) (*RotateOIakCertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateOIakCert not implemented")
}
func (UnimplementedTpmEnrollzServiceServer) RotateAIKCert(TpmEnrollzService_RotateAIKCertServer) error {
	return status.Errorf(codes.Unimplemented, "method RotateAIKCert not implemented")
}
func (UnimplementedTpmEnrollzServiceServer) mustEmbedUnimplementedTpmEnrollzServiceServer() {}

// UnsafeTpmEnrollzServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TpmEnrollzServiceServer will
// result in compilation errors.
type UnsafeTpmEnrollzServiceServer interface {
	mustEmbedUnimplementedTpmEnrollzServiceServer()
}

func RegisterTpmEnrollzServiceServer(s grpc.ServiceRegistrar, srv TpmEnrollzServiceServer) {
	s.RegisterService(&TpmEnrollzService_ServiceDesc, srv)
}

func _TpmEnrollzService_GetIakCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIakCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmEnrollzServiceServer).GetIakCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openconfig.attestz.TpmEnrollzService/GetIakCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmEnrollzServiceServer).GetIakCert(ctx, req.(*GetIakCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TpmEnrollzService_RotateOIakCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateOIakCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmEnrollzServiceServer).RotateOIakCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openconfig.attestz.TpmEnrollzService/RotateOIakCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmEnrollzServiceServer).RotateOIakCert(ctx, req.(*RotateOIakCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TpmEnrollzService_RotateAIKCert_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TpmEnrollzServiceServer).RotateAIKCert(&tpmEnrollzServiceRotateAIKCertServer{stream})
}

type TpmEnrollzService_RotateAIKCertServer interface {
	Send(*RotateAIKCertResponse) error
	Recv() (*RotateAIKCertRequest, error)
	grpc.ServerStream
}

type tpmEnrollzServiceRotateAIKCertServer struct {
	grpc.ServerStream
}

func (x *tpmEnrollzServiceRotateAIKCertServer) Send(m *RotateAIKCertResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tpmEnrollzServiceRotateAIKCertServer) Recv() (*RotateAIKCertRequest, error) {
	m := new(RotateAIKCertRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TpmEnrollzService_ServiceDesc is the grpc.ServiceDesc for TpmEnrollzService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TpmEnrollzService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openconfig.attestz.TpmEnrollzService",
	HandlerType: (*TpmEnrollzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIakCert",
			Handler:    _TpmEnrollzService_GetIakCert_Handler,
		},
		{
			MethodName: "RotateOIakCert",
			Handler:    _TpmEnrollzService_RotateOIakCert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RotateAIKCert",
			Handler:       _TpmEnrollzService_RotateAIKCert_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/openconfig/attestz/proto/tpm_enrollz.proto",
}
